// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	group "zchat/internal/group"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockChannelLookup is an autogenerated mock type for the ChannelLookup type
type MockChannelLookup struct {
	mock.Mock
}

type MockChannelLookup_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChannelLookup) EXPECT() *MockChannelLookup_Expecter {
	return &MockChannelLookup_Expecter{mock: &_m.Mock}
}

// AssertGroupMember provides a mock function with given fields: ctx, groupID, userID
func (_m *MockChannelLookup) AssertGroupMember(ctx context.Context, groupID uuid.UUID, userID uuid.UUID) error {
	ret := _m.Called(ctx, groupID, userID)

	if len(ret) == 0 {
		panic("no return value specified for AssertGroupMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, groupID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockChannelLookup_AssertGroupMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssertGroupMember'
type MockChannelLookup_AssertGroupMember_Call struct {
	*mock.Call
}

// AssertGroupMember is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID uuid.UUID
//   - userID uuid.UUID
func (_e *MockChannelLookup_Expecter) AssertGroupMember(ctx interface{}, groupID interface{}, userID interface{}) *MockChannelLookup_AssertGroupMember_Call {
	return &MockChannelLookup_AssertGroupMember_Call{Call: _e.mock.On("AssertGroupMember", ctx, groupID, userID)}
}

func (_c *MockChannelLookup_AssertGroupMember_Call) Run(run func(ctx context.Context, groupID uuid.UUID, userID uuid.UUID)) *MockChannelLookup_AssertGroupMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockChannelLookup_AssertGroupMember_Call) Return(_a0 error) *MockChannelLookup_AssertGroupMember_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChannelLookup_AssertGroupMember_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockChannelLookup_AssertGroupMember_Call {
	_c.Call.Return(run)
	return _c
}

// GetChannel provides a mock function with given fields: ctx, channelID
func (_m *MockChannelLookup) GetChannel(ctx context.Context, channelID uuid.UUID) (*group.Channel, error) {
	ret := _m.Called(ctx, channelID)

	if len(ret) == 0 {
		panic("no return value specified for GetChannel")
	}

	var r0 *group.Channel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*group.Channel, error)); ok {
		return rf(ctx, channelID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *group.Channel); ok {
		r0 = rf(ctx, channelID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*group.Channel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, channelID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChannelLookup_GetChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChannel'
type MockChannelLookup_GetChannel_Call struct {
	*mock.Call
}

// GetChannel is a helper method to define mock.On call
//   - ctx context.Context
//   - channelID uuid.UUID
func (_e *MockChannelLookup_Expecter) GetChannel(ctx interface{}, channelID interface{}) *MockChannelLookup_GetChannel_Call {
	return &MockChannelLookup_GetChannel_Call{Call: _e.mock.On("GetChannel", ctx, channelID)}
}

func (_c *MockChannelLookup_GetChannel_Call) Run(run func(ctx context.Context, channelID uuid.UUID)) *MockChannelLookup_GetChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockChannelLookup_GetChannel_Call) Return(_a0 *group.Channel, _a1 error) *MockChannelLookup_GetChannel_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChannelLookup_GetChannel_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*group.Channel, error)) *MockChannelLookup_GetChannel_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockChannelLookup creates a new instance of MockChannelLookup. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChannelLookup(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChannelLookup {
	mock := &MockChannelLookup{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
