// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	time "time"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"

	voice "zchat/internal/voice"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, event
func (_m *MockRepository) Create(ctx context.Context, event *voice.ModerationEvent) error {
	ret := _m.Called(ctx, event)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *voice.ModerationEvent) error); ok {
		r0 = rf(ctx, event)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - event *voice.ModerationEvent
func (_e *MockRepository_Expecter) Create(ctx interface{}, event interface{}) *MockRepository_Create_Call {
	return &MockRepository_Create_Call{Call: _e.mock.On("Create", ctx, event)}
}

func (_c *MockRepository_Create_Call) Run(run func(ctx context.Context, event *voice.ModerationEvent)) *MockRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*voice.ModerationEvent))
	})
	return _c
}

func (_c *MockRepository_Create_Call) Return(_a0 error) *MockRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_Create_Call) RunAndReturn(run func(context.Context, *voice.ModerationEvent) error) *MockRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function with given fields: ctx, channelID, from, to, cursor, limit
func (_m *MockRepository) List(ctx context.Context, channelID uuid.UUID, from *time.Time, to *time.Time, cursor *voice.Cursor, limit int) ([]voice.ModerationEvent, error) {
	ret := _m.Called(ctx, channelID, from, to, cursor, limit)

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []voice.ModerationEvent
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *time.Time, *time.Time, *voice.Cursor, int) ([]voice.ModerationEvent, error)); ok {
		return rf(ctx, channelID, from, to, cursor, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, *time.Time, *time.Time, *voice.Cursor, int) []voice.ModerationEvent); ok {
		r0 = rf(ctx, channelID, from, to, cursor, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]voice.ModerationEvent)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, *time.Time, *time.Time, *voice.Cursor, int) error); ok {
		r1 = rf(ctx, channelID, from, to, cursor, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - channelID uuid.UUID
//   - from *time.Time
//   - to *time.Time
//   - cursor *voice.Cursor
//   - limit int
func (_e *MockRepository_Expecter) List(ctx interface{}, channelID interface{}, from interface{}, to interface{}, cursor interface{}, limit interface{}) *MockRepository_List_Call {
	return &MockRepository_List_Call{Call: _e.mock.On("List", ctx, channelID, from, to, cursor, limit)}
}

func (_c *MockRepository_List_Call) Run(run func(ctx context.Context, channelID uuid.UUID, from *time.Time, to *time.Time, cursor *voice.Cursor, limit int)) *MockRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(*time.Time), args[3].(*time.Time), args[4].(*voice.Cursor), args[5].(int))
	})
	return _c
}

func (_c *MockRepository_List_Call) Return(_a0 []voice.ModerationEvent, _a1 error) *MockRepository_List_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_List_Call) RunAndReturn(run func(context.Context, uuid.UUID, *time.Time, *time.Time, *voice.Cursor, int) ([]voice.ModerationEvent, error)) *MockRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
