// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	auth "zchat/internal/auth"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockTokenRepository is an autogenerated mock type for the TokenRepository type
type MockTokenRepository struct {
	mock.Mock
}

type MockTokenRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenRepository) EXPECT() *MockTokenRepository_Expecter {
	return &MockTokenRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: ctx, token
func (_m *MockTokenRepository) Create(ctx context.Context, token *auth.RefreshToken) error {
	ret := _m.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *auth.RefreshToken) error); ok {
		r0 = rf(ctx, token)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTokenRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockTokenRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - token *auth.RefreshToken
func (_e *MockTokenRepository_Expecter) Create(ctx interface{}, token interface{}) *MockTokenRepository_Create_Call {
	return &MockTokenRepository_Create_Call{Call: _e.mock.On("Create", ctx, token)}
}

func (_c *MockTokenRepository_Create_Call) Run(run func(ctx context.Context, token *auth.RefreshToken)) *MockTokenRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*auth.RefreshToken))
	})
	return _c
}

func (_c *MockTokenRepository_Create_Call) Return(_a0 error) *MockTokenRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTokenRepository_Create_Call) RunAndReturn(run func(context.Context, *auth.RefreshToken) error) *MockTokenRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// GetByHash provides a mock function with given fields: ctx, tokenHash
func (_m *MockTokenRepository) GetByHash(ctx context.Context, tokenHash string) (*auth.RefreshToken, error) {
	ret := _m.Called(ctx, tokenHash)

	if len(ret) == 0 {
		panic("no return value specified for GetByHash")
	}

	var r0 *auth.RefreshToken
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*auth.RefreshToken, error)); ok {
		return rf(ctx, tokenHash)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *auth.RefreshToken); ok {
		r0 = rf(ctx, tokenHash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.RefreshToken)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, tokenHash)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenRepository_GetByHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByHash'
type MockTokenRepository_GetByHash_Call struct {
	*mock.Call
}

// GetByHash is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
func (_e *MockTokenRepository_Expecter) GetByHash(ctx interface{}, tokenHash interface{}) *MockTokenRepository_GetByHash_Call {
	return &MockTokenRepository_GetByHash_Call{Call: _e.mock.On("GetByHash", ctx, tokenHash)}
}

func (_c *MockTokenRepository_GetByHash_Call) Run(run func(ctx context.Context, tokenHash string)) *MockTokenRepository_GetByHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTokenRepository_GetByHash_Call) Return(_a0 *auth.RefreshToken, _a1 error) *MockTokenRepository_GetByHash_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenRepository_GetByHash_Call) RunAndReturn(run func(context.Context, string) (*auth.RefreshToken, error)) *MockTokenRepository_GetByHash_Call {
	_c.Call.Return(run)
	return _c
}

// Revoke provides a mock function with given fields: ctx, id
func (_m *MockTokenRepository) Revoke(ctx context.Context, id uuid.UUID) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Revoke")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockTokenRepository_Revoke_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Revoke'
type MockTokenRepository_Revoke_Call struct {
	*mock.Call
}

// Revoke is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
func (_e *MockTokenRepository_Expecter) Revoke(ctx interface{}, id interface{}) *MockTokenRepository_Revoke_Call {
	return &MockTokenRepository_Revoke_Call{Call: _e.mock.On("Revoke", ctx, id)}
}

func (_c *MockTokenRepository_Revoke_Call) Run(run func(ctx context.Context, id uuid.UUID)) *MockTokenRepository_Revoke_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockTokenRepository_Revoke_Call) Return(_a0 error) *MockTokenRepository_Revoke_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTokenRepository_Revoke_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockTokenRepository_Revoke_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenRepository creates a new instance of MockTokenRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenRepository {
	mock := &MockTokenRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
