// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	auth "zchat/internal/auth"

	mock "github.com/stretchr/testify/mock"
)

// MockAccessTokenValidator is an autogenerated mock type for the AccessTokenValidator type
type MockAccessTokenValidator struct {
	mock.Mock
}

type MockAccessTokenValidator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAccessTokenValidator) EXPECT() *MockAccessTokenValidator_Expecter {
	return &MockAccessTokenValidator_Expecter{mock: &_m.Mock}
}

// ValidateAccessToken provides a mock function with given fields: tokenStr
func (_m *MockAccessTokenValidator) ValidateAccessToken(tokenStr string) (*auth.Claims, error) {
	ret := _m.Called(tokenStr)

	if len(ret) == 0 {
		panic("no return value specified for ValidateAccessToken")
	}

	var r0 *auth.Claims
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*auth.Claims, error)); ok {
		return rf(tokenStr)
	}
	if rf, ok := ret.Get(0).(func(string) *auth.Claims); ok {
		r0 = rf(tokenStr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.Claims)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(tokenStr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockAccessTokenValidator_ValidateAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateAccessToken'
type MockAccessTokenValidator_ValidateAccessToken_Call struct {
	*mock.Call
}

// ValidateAccessToken is a helper method to define mock.On call
//   - tokenStr string
func (_e *MockAccessTokenValidator_Expecter) ValidateAccessToken(tokenStr interface{}) *MockAccessTokenValidator_ValidateAccessToken_Call {
	return &MockAccessTokenValidator_ValidateAccessToken_Call{Call: _e.mock.On("ValidateAccessToken", tokenStr)}
}

func (_c *MockAccessTokenValidator_ValidateAccessToken_Call) Run(run func(tokenStr string)) *MockAccessTokenValidator_ValidateAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockAccessTokenValidator_ValidateAccessToken_Call) Return(_a0 *auth.Claims, _a1 error) *MockAccessTokenValidator_ValidateAccessToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAccessTokenValidator_ValidateAccessToken_Call) RunAndReturn(run func(string) (*auth.Claims, error)) *MockAccessTokenValidator_ValidateAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAccessTokenValidator creates a new instance of MockAccessTokenValidator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAccessTokenValidator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAccessTokenValidator {
	mock := &MockAccessTokenValidator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
