// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	auth "zchat/internal/auth"

	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// MockTokenGenerator is an autogenerated mock type for the TokenGenerator type
type MockTokenGenerator struct {
	mock.Mock
}

type MockTokenGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTokenGenerator) EXPECT() *MockTokenGenerator_Expecter {
	return &MockTokenGenerator_Expecter{mock: &_m.Mock}
}

// GenerateTokenPair provides a mock function with given fields: user
func (_m *MockTokenGenerator) GenerateTokenPair(user *auth.User) (*auth.TokenPair, error) {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for GenerateTokenPair")
	}

	var r0 *auth.TokenPair
	var r1 error
	if rf, ok := ret.Get(0).(func(*auth.User) (*auth.TokenPair, error)); ok {
		return rf(user)
	}
	if rf, ok := ret.Get(0).(func(*auth.User) *auth.TokenPair); ok {
		r0 = rf(user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.TokenPair)
		}
	}

	if rf, ok := ret.Get(1).(func(*auth.User) error); ok {
		r1 = rf(user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenGenerator_GenerateTokenPair_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GenerateTokenPair'
type MockTokenGenerator_GenerateTokenPair_Call struct {
	*mock.Call
}

// GenerateTokenPair is a helper method to define mock.On call
//   - user *auth.User
func (_e *MockTokenGenerator_Expecter) GenerateTokenPair(user interface{}) *MockTokenGenerator_GenerateTokenPair_Call {
	return &MockTokenGenerator_GenerateTokenPair_Call{Call: _e.mock.On("GenerateTokenPair", user)}
}

func (_c *MockTokenGenerator_GenerateTokenPair_Call) Run(run func(user *auth.User)) *MockTokenGenerator_GenerateTokenPair_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*auth.User))
	})
	return _c
}

func (_c *MockTokenGenerator_GenerateTokenPair_Call) Return(_a0 *auth.TokenPair, _a1 error) *MockTokenGenerator_GenerateTokenPair_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenGenerator_GenerateTokenPair_Call) RunAndReturn(run func(*auth.User) (*auth.TokenPair, error)) *MockTokenGenerator_GenerateTokenPair_Call {
	_c.Call.Return(run)
	return _c
}

// HashToken provides a mock function with given fields: token
func (_m *MockTokenGenerator) HashToken(token string) string {
	ret := _m.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for HashToken")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(token)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockTokenGenerator_HashToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HashToken'
type MockTokenGenerator_HashToken_Call struct {
	*mock.Call
}

// HashToken is a helper method to define mock.On call
//   - token string
func (_e *MockTokenGenerator_Expecter) HashToken(token interface{}) *MockTokenGenerator_HashToken_Call {
	return &MockTokenGenerator_HashToken_Call{Call: _e.mock.On("HashToken", token)}
}

func (_c *MockTokenGenerator_HashToken_Call) Run(run func(token string)) *MockTokenGenerator_HashToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockTokenGenerator_HashToken_Call) Return(_a0 string) *MockTokenGenerator_HashToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTokenGenerator_HashToken_Call) RunAndReturn(run func(string) string) *MockTokenGenerator_HashToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewRefreshToken provides a mock function with given fields: userID, tokenStr
func (_m *MockTokenGenerator) NewRefreshToken(userID uuid.UUID, tokenStr string) *auth.RefreshToken {
	ret := _m.Called(userID, tokenStr)

	if len(ret) == 0 {
		panic("no return value specified for NewRefreshToken")
	}

	var r0 *auth.RefreshToken
	if rf, ok := ret.Get(0).(func(uuid.UUID, string) *auth.RefreshToken); ok {
		r0 = rf(userID, tokenStr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.RefreshToken)
		}
	}

	return r0
}

// MockTokenGenerator_NewRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewRefreshToken'
type MockTokenGenerator_NewRefreshToken_Call struct {
	*mock.Call
}

// NewRefreshToken is a helper method to define mock.On call
//   - userID uuid.UUID
//   - tokenStr string
func (_e *MockTokenGenerator_Expecter) NewRefreshToken(userID interface{}, tokenStr interface{}) *MockTokenGenerator_NewRefreshToken_Call {
	return &MockTokenGenerator_NewRefreshToken_Call{Call: _e.mock.On("NewRefreshToken", userID, tokenStr)}
}

func (_c *MockTokenGenerator_NewRefreshToken_Call) Run(run func(userID uuid.UUID, tokenStr string)) *MockTokenGenerator_NewRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(uuid.UUID), args[1].(string))
	})
	return _c
}

func (_c *MockTokenGenerator_NewRefreshToken_Call) Return(_a0 *auth.RefreshToken) *MockTokenGenerator_NewRefreshToken_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockTokenGenerator_NewRefreshToken_Call) RunAndReturn(run func(uuid.UUID, string) *auth.RefreshToken) *MockTokenGenerator_NewRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateAccessToken provides a mock function with given fields: tokenStr
func (_m *MockTokenGenerator) ValidateAccessToken(tokenStr string) (*auth.Claims, error) {
	ret := _m.Called(tokenStr)

	if len(ret) == 0 {
		panic("no return value specified for ValidateAccessToken")
	}

	var r0 *auth.Claims
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*auth.Claims, error)); ok {
		return rf(tokenStr)
	}
	if rf, ok := ret.Get(0).(func(string) *auth.Claims); ok {
		r0 = rf(tokenStr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.Claims)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(tokenStr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenGenerator_ValidateAccessToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateAccessToken'
type MockTokenGenerator_ValidateAccessToken_Call struct {
	*mock.Call
}

// ValidateAccessToken is a helper method to define mock.On call
//   - tokenStr string
func (_e *MockTokenGenerator_Expecter) ValidateAccessToken(tokenStr interface{}) *MockTokenGenerator_ValidateAccessToken_Call {
	return &MockTokenGenerator_ValidateAccessToken_Call{Call: _e.mock.On("ValidateAccessToken", tokenStr)}
}

func (_c *MockTokenGenerator_ValidateAccessToken_Call) Run(run func(tokenStr string)) *MockTokenGenerator_ValidateAccessToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockTokenGenerator_ValidateAccessToken_Call) Return(_a0 *auth.Claims, _a1 error) *MockTokenGenerator_ValidateAccessToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenGenerator_ValidateAccessToken_Call) RunAndReturn(run func(string) (*auth.Claims, error)) *MockTokenGenerator_ValidateAccessToken_Call {
	_c.Call.Return(run)
	return _c
}

// ValidateRefreshToken provides a mock function with given fields: tokenStr
func (_m *MockTokenGenerator) ValidateRefreshToken(tokenStr string) (*auth.Claims, error) {
	ret := _m.Called(tokenStr)

	if len(ret) == 0 {
		panic("no return value specified for ValidateRefreshToken")
	}

	var r0 *auth.Claims
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*auth.Claims, error)); ok {
		return rf(tokenStr)
	}
	if rf, ok := ret.Get(0).(func(string) *auth.Claims); ok {
		r0 = rf(tokenStr)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.Claims)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(tokenStr)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTokenGenerator_ValidateRefreshToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ValidateRefreshToken'
type MockTokenGenerator_ValidateRefreshToken_Call struct {
	*mock.Call
}

// ValidateRefreshToken is a helper method to define mock.On call
//   - tokenStr string
func (_e *MockTokenGenerator_Expecter) ValidateRefreshToken(tokenStr interface{}) *MockTokenGenerator_ValidateRefreshToken_Call {
	return &MockTokenGenerator_ValidateRefreshToken_Call{Call: _e.mock.On("ValidateRefreshToken", tokenStr)}
}

func (_c *MockTokenGenerator_ValidateRefreshToken_Call) Run(run func(tokenStr string)) *MockTokenGenerator_ValidateRefreshToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockTokenGenerator_ValidateRefreshToken_Call) Return(_a0 *auth.Claims, _a1 error) *MockTokenGenerator_ValidateRefreshToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTokenGenerator_ValidateRefreshToken_Call) RunAndReturn(run func(string) (*auth.Claims, error)) *MockTokenGenerator_ValidateRefreshToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTokenGenerator creates a new instance of MockTokenGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTokenGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTokenGenerator {
	mock := &MockTokenGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
