// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	group "zchat/internal/group"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// AddMember provides a mock function with given fields: ctx, groupID, userID, role
func (_m *MockRepository) AddMember(ctx context.Context, groupID uuid.UUID, userID uuid.UUID, role group.Role) error {
	ret := _m.Called(ctx, groupID, userID, role)

	if len(ret) == 0 {
		panic("no return value specified for AddMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, group.Role) error); ok {
		r0 = rf(ctx, groupID, userID, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_AddMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddMember'
type MockRepository_AddMember_Call struct {
	*mock.Call
}

// AddMember is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID uuid.UUID
//   - userID uuid.UUID
//   - role group.Role
func (_e *MockRepository_Expecter) AddMember(ctx interface{}, groupID interface{}, userID interface{}, role interface{}) *MockRepository_AddMember_Call {
	return &MockRepository_AddMember_Call{Call: _e.mock.On("AddMember", ctx, groupID, userID, role)}
}

func (_c *MockRepository_AddMember_Call) Run(run func(ctx context.Context, groupID uuid.UUID, userID uuid.UUID, role group.Role)) *MockRepository_AddMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(group.Role))
	})
	return _c
}

func (_c *MockRepository_AddMember_Call) Return(_a0 error) *MockRepository_AddMember_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_AddMember_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, group.Role) error) *MockRepository_AddMember_Call {
	_c.Call.Return(run)
	return _c
}

// CreateChannel provides a mock function with given fields: ctx, channel
func (_m *MockRepository) CreateChannel(ctx context.Context, channel *group.Channel) error {
	ret := _m.Called(ctx, channel)

	if len(ret) == 0 {
		panic("no return value specified for CreateChannel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *group.Channel) error); ok {
		r0 = rf(ctx, channel)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_CreateChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateChannel'
type MockRepository_CreateChannel_Call struct {
	*mock.Call
}

// CreateChannel is a helper method to define mock.On call
//   - ctx context.Context
//   - channel *group.Channel
func (_e *MockRepository_Expecter) CreateChannel(ctx interface{}, channel interface{}) *MockRepository_CreateChannel_Call {
	return &MockRepository_CreateChannel_Call{Call: _e.mock.On("CreateChannel", ctx, channel)}
}

func (_c *MockRepository_CreateChannel_Call) Run(run func(ctx context.Context, channel *group.Channel)) *MockRepository_CreateChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*group.Channel))
	})
	return _c
}

func (_c *MockRepository_CreateChannel_Call) Return(_a0 error) *MockRepository_CreateChannel_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_CreateChannel_Call) RunAndReturn(run func(context.Context, *group.Channel) error) *MockRepository_CreateChannel_Call {
	_c.Call.Return(run)
	return _c
}

// CreateGroup provides a mock function with given fields: ctx, _a1
func (_m *MockRepository) CreateGroup(ctx context.Context, _a1 *group.Group) error {
	ret := _m.Called(ctx, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CreateGroup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *group.Group) error); ok {
		r0 = rf(ctx, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_CreateGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateGroup'
type MockRepository_CreateGroup_Call struct {
	*mock.Call
}

// CreateGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - _a1 *group.Group
func (_e *MockRepository_Expecter) CreateGroup(ctx interface{}, _a1 interface{}) *MockRepository_CreateGroup_Call {
	return &MockRepository_CreateGroup_Call{Call: _e.mock.On("CreateGroup", ctx, _a1)}
}

func (_c *MockRepository_CreateGroup_Call) Run(run func(ctx context.Context, _a1 *group.Group)) *MockRepository_CreateGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*group.Group))
	})
	return _c
}

func (_c *MockRepository_CreateGroup_Call) Return(_a0 error) *MockRepository_CreateGroup_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_CreateGroup_Call) RunAndReturn(run func(context.Context, *group.Group) error) *MockRepository_CreateGroup_Call {
	_c.Call.Return(run)
	return _c
}

// GetChannelByID provides a mock function with given fields: ctx, channelID
func (_m *MockRepository) GetChannelByID(ctx context.Context, channelID uuid.UUID) (*group.Channel, error) {
	ret := _m.Called(ctx, channelID)

	if len(ret) == 0 {
		panic("no return value specified for GetChannelByID")
	}

	var r0 *group.Channel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*group.Channel, error)); ok {
		return rf(ctx, channelID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *group.Channel); ok {
		r0 = rf(ctx, channelID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*group.Channel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, channelID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetChannelByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetChannelByID'
type MockRepository_GetChannelByID_Call struct {
	*mock.Call
}

// GetChannelByID is a helper method to define mock.On call
//   - ctx context.Context
//   - channelID uuid.UUID
func (_e *MockRepository_Expecter) GetChannelByID(ctx interface{}, channelID interface{}) *MockRepository_GetChannelByID_Call {
	return &MockRepository_GetChannelByID_Call{Call: _e.mock.On("GetChannelByID", ctx, channelID)}
}

func (_c *MockRepository_GetChannelByID_Call) Run(run func(ctx context.Context, channelID uuid.UUID)) *MockRepository_GetChannelByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_GetChannelByID_Call) Return(_a0 *group.Channel, _a1 error) *MockRepository_GetChannelByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetChannelByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*group.Channel, error)) *MockRepository_GetChannelByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetGroupByID provides a mock function with given fields: ctx, groupID
func (_m *MockRepository) GetGroupByID(ctx context.Context, groupID uuid.UUID) (*group.Group, error) {
	ret := _m.Called(ctx, groupID)

	if len(ret) == 0 {
		panic("no return value specified for GetGroupByID")
	}

	var r0 *group.Group
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*group.Group, error)); ok {
		return rf(ctx, groupID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *group.Group); ok {
		r0 = rf(ctx, groupID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*group.Group)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, groupID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetGroupByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGroupByID'
type MockRepository_GetGroupByID_Call struct {
	*mock.Call
}

// GetGroupByID is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID uuid.UUID
func (_e *MockRepository_Expecter) GetGroupByID(ctx interface{}, groupID interface{}) *MockRepository_GetGroupByID_Call {
	return &MockRepository_GetGroupByID_Call{Call: _e.mock.On("GetGroupByID", ctx, groupID)}
}

func (_c *MockRepository_GetGroupByID_Call) Run(run func(ctx context.Context, groupID uuid.UUID)) *MockRepository_GetGroupByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_GetGroupByID_Call) Return(_a0 *group.Group, _a1 error) *MockRepository_GetGroupByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetGroupByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*group.Group, error)) *MockRepository_GetGroupByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetMember provides a mock function with given fields: ctx, groupID, userID
func (_m *MockRepository) GetMember(ctx context.Context, groupID uuid.UUID, userID uuid.UUID) (*group.Member, error) {
	ret := _m.Called(ctx, groupID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetMember")
	}

	var r0 *group.Member
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*group.Member, error)); ok {
		return rf(ctx, groupID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *group.Member); ok {
		r0 = rf(ctx, groupID, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*group.Member)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, groupID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMember'
type MockRepository_GetMember_Call struct {
	*mock.Call
}

// GetMember is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID uuid.UUID
//   - userID uuid.UUID
func (_e *MockRepository_Expecter) GetMember(ctx interface{}, groupID interface{}, userID interface{}) *MockRepository_GetMember_Call {
	return &MockRepository_GetMember_Call{Call: _e.mock.On("GetMember", ctx, groupID, userID)}
}

func (_c *MockRepository_GetMember_Call) Run(run func(ctx context.Context, groupID uuid.UUID, userID uuid.UUID)) *MockRepository_GetMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_GetMember_Call) Return(_a0 *group.Member, _a1 error) *MockRepository_GetMember_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetMember_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*group.Member, error)) *MockRepository_GetMember_Call {
	_c.Call.Return(run)
	return _c
}

// GetMemberRole provides a mock function with given fields: ctx, groupID, userID
func (_m *MockRepository) GetMemberRole(ctx context.Context, groupID uuid.UUID, userID uuid.UUID) (group.Role, error) {
	ret := _m.Called(ctx, groupID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetMemberRole")
	}

	var r0 group.Role
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (group.Role, error)); ok {
		return rf(ctx, groupID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) group.Role); ok {
		r0 = rf(ctx, groupID, userID)
	} else {
		r0 = ret.Get(0).(group.Role)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, groupID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetMemberRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMemberRole'
type MockRepository_GetMemberRole_Call struct {
	*mock.Call
}

// GetMemberRole is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID uuid.UUID
//   - userID uuid.UUID
func (_e *MockRepository_Expecter) GetMemberRole(ctx interface{}, groupID interface{}, userID interface{}) *MockRepository_GetMemberRole_Call {
	return &MockRepository_GetMemberRole_Call{Call: _e.mock.On("GetMemberRole", ctx, groupID, userID)}
}

func (_c *MockRepository_GetMemberRole_Call) Run(run func(ctx context.Context, groupID uuid.UUID, userID uuid.UUID)) *MockRepository_GetMemberRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_GetMemberRole_Call) Return(_a0 group.Role, _a1 error) *MockRepository_GetMemberRole_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetMemberRole_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (group.Role, error)) *MockRepository_GetMemberRole_Call {
	_c.Call.Return(run)
	return _c
}

// IsMember provides a mock function with given fields: ctx, groupID, userID
func (_m *MockRepository) IsMember(ctx context.Context, groupID uuid.UUID, userID uuid.UUID) (bool, error) {
	ret := _m.Called(ctx, groupID, userID)

	if len(ret) == 0 {
		panic("no return value specified for IsMember")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (bool, error)); ok {
		return rf(ctx, groupID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) bool); ok {
		r0 = rf(ctx, groupID, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, groupID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_IsMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsMember'
type MockRepository_IsMember_Call struct {
	*mock.Call
}

// IsMember is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID uuid.UUID
//   - userID uuid.UUID
func (_e *MockRepository_Expecter) IsMember(ctx interface{}, groupID interface{}, userID interface{}) *MockRepository_IsMember_Call {
	return &MockRepository_IsMember_Call{Call: _e.mock.On("IsMember", ctx, groupID, userID)}
}

func (_c *MockRepository_IsMember_Call) Run(run func(ctx context.Context, groupID uuid.UUID, userID uuid.UUID)) *MockRepository_IsMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_IsMember_Call) Return(_a0 bool, _a1 error) *MockRepository_IsMember_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_IsMember_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (bool, error)) *MockRepository_IsMember_Call {
	_c.Call.Return(run)
	return _c
}

// ListGroupChannels provides a mock function with given fields: ctx, groupID
func (_m *MockRepository) ListGroupChannels(ctx context.Context, groupID uuid.UUID) ([]group.Channel, error) {
	ret := _m.Called(ctx, groupID)

	if len(ret) == 0 {
		panic("no return value specified for ListGroupChannels")
	}

	var r0 []group.Channel
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]group.Channel, error)); ok {
		return rf(ctx, groupID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []group.Channel); ok {
		r0 = rf(ctx, groupID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]group.Channel)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, groupID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListGroupChannels_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListGroupChannels'
type MockRepository_ListGroupChannels_Call struct {
	*mock.Call
}

// ListGroupChannels is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID uuid.UUID
func (_e *MockRepository_Expecter) ListGroupChannels(ctx interface{}, groupID interface{}) *MockRepository_ListGroupChannels_Call {
	return &MockRepository_ListGroupChannels_Call{Call: _e.mock.On("ListGroupChannels", ctx, groupID)}
}

func (_c *MockRepository_ListGroupChannels_Call) Run(run func(ctx context.Context, groupID uuid.UUID)) *MockRepository_ListGroupChannels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_ListGroupChannels_Call) Return(_a0 []group.Channel, _a1 error) *MockRepository_ListGroupChannels_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListGroupChannels_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]group.Channel, error)) *MockRepository_ListGroupChannels_Call {
	_c.Call.Return(run)
	return _c
}

// ListMembers provides a mock function with given fields: ctx, groupID
func (_m *MockRepository) ListMembers(ctx context.Context, groupID uuid.UUID) ([]group.Member, error) {
	ret := _m.Called(ctx, groupID)

	if len(ret) == 0 {
		panic("no return value specified for ListMembers")
	}

	var r0 []group.Member
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]group.Member, error)); ok {
		return rf(ctx, groupID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []group.Member); ok {
		r0 = rf(ctx, groupID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]group.Member)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, groupID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListMembers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListMembers'
type MockRepository_ListMembers_Call struct {
	*mock.Call
}

// ListMembers is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID uuid.UUID
func (_e *MockRepository_Expecter) ListMembers(ctx interface{}, groupID interface{}) *MockRepository_ListMembers_Call {
	return &MockRepository_ListMembers_Call{Call: _e.mock.On("ListMembers", ctx, groupID)}
}

func (_c *MockRepository_ListMembers_Call) Run(run func(ctx context.Context, groupID uuid.UUID)) *MockRepository_ListMembers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_ListMembers_Call) Return(_a0 []group.Member, _a1 error) *MockRepository_ListMembers_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListMembers_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]group.Member, error)) *MockRepository_ListMembers_Call {
	_c.Call.Return(run)
	return _c
}

// ListUserGroups provides a mock function with given fields: ctx, userID
func (_m *MockRepository) ListUserGroups(ctx context.Context, userID uuid.UUID) ([]group.Group, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListUserGroups")
	}

	var r0 []group.Group
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]group.Group, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []group.Group); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]group.Group)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListUserGroups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUserGroups'
type MockRepository_ListUserGroups_Call struct {
	*mock.Call
}

// ListUserGroups is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockRepository_Expecter) ListUserGroups(ctx interface{}, userID interface{}) *MockRepository_ListUserGroups_Call {
	return &MockRepository_ListUserGroups_Call{Call: _e.mock.On("ListUserGroups", ctx, userID)}
}

func (_c *MockRepository_ListUserGroups_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockRepository_ListUserGroups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_ListUserGroups_Call) Return(_a0 []group.Group, _a1 error) *MockRepository_ListUserGroups_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListUserGroups_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]group.Group, error)) *MockRepository_ListUserGroups_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveMember provides a mock function with given fields: ctx, groupID, userID
func (_m *MockRepository) RemoveMember(ctx context.Context, groupID uuid.UUID, userID uuid.UUID) error {
	ret := _m.Called(ctx, groupID, userID)

	if len(ret) == 0 {
		panic("no return value specified for RemoveMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, groupID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_RemoveMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveMember'
type MockRepository_RemoveMember_Call struct {
	*mock.Call
}

// RemoveMember is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID uuid.UUID
//   - userID uuid.UUID
func (_e *MockRepository_Expecter) RemoveMember(ctx interface{}, groupID interface{}, userID interface{}) *MockRepository_RemoveMember_Call {
	return &MockRepository_RemoveMember_Call{Call: _e.mock.On("RemoveMember", ctx, groupID, userID)}
}

func (_c *MockRepository_RemoveMember_Call) Run(run func(ctx context.Context, groupID uuid.UUID, userID uuid.UUID)) *MockRepository_RemoveMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_RemoveMember_Call) Return(_a0 error) *MockRepository_RemoveMember_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_RemoveMember_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockRepository_RemoveMember_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateMemberRole provides a mock function with given fields: ctx, groupID, userID, role
func (_m *MockRepository) UpdateMemberRole(ctx context.Context, groupID uuid.UUID, userID uuid.UUID, role group.Role) error {
	ret := _m.Called(ctx, groupID, userID, role)

	if len(ret) == 0 {
		panic("no return value specified for UpdateMemberRole")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, group.Role) error); ok {
		r0 = rf(ctx, groupID, userID, role)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_UpdateMemberRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateMemberRole'
type MockRepository_UpdateMemberRole_Call struct {
	*mock.Call
}

// UpdateMemberRole is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID uuid.UUID
//   - userID uuid.UUID
//   - role group.Role
func (_e *MockRepository_Expecter) UpdateMemberRole(ctx interface{}, groupID interface{}, userID interface{}, role interface{}) *MockRepository_UpdateMemberRole_Call {
	return &MockRepository_UpdateMemberRole_Call{Call: _e.mock.On("UpdateMemberRole", ctx, groupID, userID, role)}
}

func (_c *MockRepository_UpdateMemberRole_Call) Run(run func(ctx context.Context, groupID uuid.UUID, userID uuid.UUID, role group.Role)) *MockRepository_UpdateMemberRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(group.Role))
	})
	return _c
}

func (_c *MockRepository_UpdateMemberRole_Call) Return(_a0 error) *MockRepository_UpdateMemberRole_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_UpdateMemberRole_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, group.Role) error) *MockRepository_UpdateMemberRole_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
