// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// MockCache is an autogenerated mock type for the Cache type
type MockCache struct {
	mock.Mock
}

type MockCache_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCache) EXPECT() *MockCache_Expecter {
	return &MockCache_Expecter{mock: &_m.Mock}
}

// DeleteGroupChannels provides a mock function with given fields: ctx, groupID
func (_m *MockCache) DeleteGroupChannels(ctx context.Context, groupID uuid.UUID) error {
	ret := _m.Called(ctx, groupID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteGroupChannels")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, groupID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCache_DeleteGroupChannels_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteGroupChannels'
type MockCache_DeleteGroupChannels_Call struct {
	*mock.Call
}

// DeleteGroupChannels is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID uuid.UUID
func (_e *MockCache_Expecter) DeleteGroupChannels(ctx interface{}, groupID interface{}) *MockCache_DeleteGroupChannels_Call {
	return &MockCache_DeleteGroupChannels_Call{Call: _e.mock.On("DeleteGroupChannels", ctx, groupID)}
}

func (_c *MockCache_DeleteGroupChannels_Call) Run(run func(ctx context.Context, groupID uuid.UUID)) *MockCache_DeleteGroupChannels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockCache_DeleteGroupChannels_Call) Return(_a0 error) *MockCache_DeleteGroupChannels_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCache_DeleteGroupChannels_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockCache_DeleteGroupChannels_Call {
	_c.Call.Return(run)
	return _c
}

// GetGroupChannels provides a mock function with given fields: ctx, groupID
func (_m *MockCache) GetGroupChannels(ctx context.Context, groupID uuid.UUID) ([]byte, bool, error) {
	ret := _m.Called(ctx, groupID)

	if len(ret) == 0 {
		panic("no return value specified for GetGroupChannels")
	}

	var r0 []byte
	var r1 bool
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]byte, bool, error)); ok {
		return rf(ctx, groupID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []byte); ok {
		r0 = rf(ctx, groupID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) bool); ok {
		r1 = rf(ctx, groupID)
	} else {
		r1 = ret.Get(1).(bool)
	}

	if rf, ok := ret.Get(2).(func(context.Context, uuid.UUID) error); ok {
		r2 = rf(ctx, groupID)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockCache_GetGroupChannels_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetGroupChannels'
type MockCache_GetGroupChannels_Call struct {
	*mock.Call
}

// GetGroupChannels is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID uuid.UUID
func (_e *MockCache_Expecter) GetGroupChannels(ctx interface{}, groupID interface{}) *MockCache_GetGroupChannels_Call {
	return &MockCache_GetGroupChannels_Call{Call: _e.mock.On("GetGroupChannels", ctx, groupID)}
}

func (_c *MockCache_GetGroupChannels_Call) Run(run func(ctx context.Context, groupID uuid.UUID)) *MockCache_GetGroupChannels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockCache_GetGroupChannels_Call) Return(_a0 []byte, _a1 bool, _a2 error) *MockCache_GetGroupChannels_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockCache_GetGroupChannels_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]byte, bool, error)) *MockCache_GetGroupChannels_Call {
	_c.Call.Return(run)
	return _c
}

// SetGroupChannels provides a mock function with given fields: ctx, groupID, payload, ttl
func (_m *MockCache) SetGroupChannels(ctx context.Context, groupID uuid.UUID, payload []byte, ttl time.Duration) error {
	ret := _m.Called(ctx, groupID, payload, ttl)

	if len(ret) == 0 {
		panic("no return value specified for SetGroupChannels")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, []byte, time.Duration) error); ok {
		r0 = rf(ctx, groupID, payload, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockCache_SetGroupChannels_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetGroupChannels'
type MockCache_SetGroupChannels_Call struct {
	*mock.Call
}

// SetGroupChannels is a helper method to define mock.On call
//   - ctx context.Context
//   - groupID uuid.UUID
//   - payload []byte
//   - ttl time.Duration
func (_e *MockCache_Expecter) SetGroupChannels(ctx interface{}, groupID interface{}, payload interface{}, ttl interface{}) *MockCache_SetGroupChannels_Call {
	return &MockCache_SetGroupChannels_Call{Call: _e.mock.On("SetGroupChannels", ctx, groupID, payload, ttl)}
}

func (_c *MockCache_SetGroupChannels_Call) Run(run func(ctx context.Context, groupID uuid.UUID, payload []byte, ttl time.Duration)) *MockCache_SetGroupChannels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].([]byte), args[3].(time.Duration))
	})
	return _c
}

func (_c *MockCache_SetGroupChannels_Call) Return(_a0 error) *MockCache_SetGroupChannels_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockCache_SetGroupChannels_Call) RunAndReturn(run func(context.Context, uuid.UUID, []byte, time.Duration) error) *MockCache_SetGroupChannels_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockCache creates a new instance of MockCache. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCache(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCache {
	mock := &MockCache{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
