// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	realtime "zchat/internal/realtime"

	mock "github.com/stretchr/testify/mock"

	time "time"

	uuid "github.com/google/uuid"
)

// MockStore is an autogenerated mock type for the Store type
type MockStore struct {
	mock.Mock
}

type MockStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockStore) EXPECT() *MockStore_Expecter {
	return &MockStore_Expecter{mock: &_m.Mock}
}

// GetUserPresence provides a mock function with given fields: ctx, userID
func (_m *MockStore) GetUserPresence(ctx context.Context, userID uuid.UUID) (*realtime.Presence, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserPresence")
	}

	var r0 *realtime.Presence
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*realtime.Presence, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *realtime.Presence); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*realtime.Presence)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_GetUserPresence_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserPresence'
type MockStore_GetUserPresence_Call struct {
	*mock.Call
}

// GetUserPresence is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockStore_Expecter) GetUserPresence(ctx interface{}, userID interface{}) *MockStore_GetUserPresence_Call {
	return &MockStore_GetUserPresence_Call{Call: _e.mock.On("GetUserPresence", ctx, userID)}
}

func (_c *MockStore_GetUserPresence_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockStore_GetUserPresence_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockStore_GetUserPresence_Call) Return(_a0 *realtime.Presence, _a1 error) *MockStore_GetUserPresence_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_GetUserPresence_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*realtime.Presence, error)) *MockStore_GetUserPresence_Call {
	_c.Call.Return(run)
	return _c
}

// GetVoiceParticipantState provides a mock function with given fields: ctx, channelID, userID
func (_m *MockStore) GetVoiceParticipantState(ctx context.Context, channelID uuid.UUID, userID uuid.UUID) (realtime.VoiceParticipantState, error) {
	ret := _m.Called(ctx, channelID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetVoiceParticipantState")
	}

	var r0 realtime.VoiceParticipantState
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (realtime.VoiceParticipantState, error)); ok {
		return rf(ctx, channelID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) realtime.VoiceParticipantState); ok {
		r0 = rf(ctx, channelID, userID)
	} else {
		r0 = ret.Get(0).(realtime.VoiceParticipantState)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, channelID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_GetVoiceParticipantState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVoiceParticipantState'
type MockStore_GetVoiceParticipantState_Call struct {
	*mock.Call
}

// GetVoiceParticipantState is a helper method to define mock.On call
//   - ctx context.Context
//   - channelID uuid.UUID
//   - userID uuid.UUID
func (_e *MockStore_Expecter) GetVoiceParticipantState(ctx interface{}, channelID interface{}, userID interface{}) *MockStore_GetVoiceParticipantState_Call {
	return &MockStore_GetVoiceParticipantState_Call{Call: _e.mock.On("GetVoiceParticipantState", ctx, channelID, userID)}
}

func (_c *MockStore_GetVoiceParticipantState_Call) Run(run func(ctx context.Context, channelID uuid.UUID, userID uuid.UUID)) *MockStore_GetVoiceParticipantState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockStore_GetVoiceParticipantState_Call) Return(_a0 realtime.VoiceParticipantState, _a1 error) *MockStore_GetVoiceParticipantState_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_GetVoiceParticipantState_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (realtime.VoiceParticipantState, error)) *MockStore_GetVoiceParticipantState_Call {
	_c.Call.Return(run)
	return _c
}

// IsVoiceParticipant provides a mock function with given fields: ctx, channelID, userID
func (_m *MockStore) IsVoiceParticipant(ctx context.Context, channelID uuid.UUID, userID uuid.UUID) (bool, error) {
	ret := _m.Called(ctx, channelID, userID)

	if len(ret) == 0 {
		panic("no return value specified for IsVoiceParticipant")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (bool, error)); ok {
		return rf(ctx, channelID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) bool); ok {
		r0 = rf(ctx, channelID, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, channelID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_IsVoiceParticipant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsVoiceParticipant'
type MockStore_IsVoiceParticipant_Call struct {
	*mock.Call
}

// IsVoiceParticipant is a helper method to define mock.On call
//   - ctx context.Context
//   - channelID uuid.UUID
//   - userID uuid.UUID
func (_e *MockStore_Expecter) IsVoiceParticipant(ctx interface{}, channelID interface{}, userID interface{}) *MockStore_IsVoiceParticipant_Call {
	return &MockStore_IsVoiceParticipant_Call{Call: _e.mock.On("IsVoiceParticipant", ctx, channelID, userID)}
}

func (_c *MockStore_IsVoiceParticipant_Call) Run(run func(ctx context.Context, channelID uuid.UUID, userID uuid.UUID)) *MockStore_IsVoiceParticipant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockStore_IsVoiceParticipant_Call) Return(_a0 bool, _a1 error) *MockStore_IsVoiceParticipant_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_IsVoiceParticipant_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (bool, error)) *MockStore_IsVoiceParticipant_Call {
	_c.Call.Return(run)
	return _c
}

// JoinVoiceChannel provides a mock function with given fields: ctx, channelID, userID
func (_m *MockStore) JoinVoiceChannel(ctx context.Context, channelID uuid.UUID, userID uuid.UUID) (bool, error) {
	ret := _m.Called(ctx, channelID, userID)

	if len(ret) == 0 {
		panic("no return value specified for JoinVoiceChannel")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (bool, error)); ok {
		return rf(ctx, channelID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) bool); ok {
		r0 = rf(ctx, channelID, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, channelID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_JoinVoiceChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'JoinVoiceChannel'
type MockStore_JoinVoiceChannel_Call struct {
	*mock.Call
}

// JoinVoiceChannel is a helper method to define mock.On call
//   - ctx context.Context
//   - channelID uuid.UUID
//   - userID uuid.UUID
func (_e *MockStore_Expecter) JoinVoiceChannel(ctx interface{}, channelID interface{}, userID interface{}) *MockStore_JoinVoiceChannel_Call {
	return &MockStore_JoinVoiceChannel_Call{Call: _e.mock.On("JoinVoiceChannel", ctx, channelID, userID)}
}

func (_c *MockStore_JoinVoiceChannel_Call) Run(run func(ctx context.Context, channelID uuid.UUID, userID uuid.UUID)) *MockStore_JoinVoiceChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockStore_JoinVoiceChannel_Call) Return(_a0 bool, _a1 error) *MockStore_JoinVoiceChannel_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_JoinVoiceChannel_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (bool, error)) *MockStore_JoinVoiceChannel_Call {
	_c.Call.Return(run)
	return _c
}

// LeaveVoiceChannel provides a mock function with given fields: ctx, channelID, userID
func (_m *MockStore) LeaveVoiceChannel(ctx context.Context, channelID uuid.UUID, userID uuid.UUID) (bool, error) {
	ret := _m.Called(ctx, channelID, userID)

	if len(ret) == 0 {
		panic("no return value specified for LeaveVoiceChannel")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (bool, error)); ok {
		return rf(ctx, channelID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) bool); ok {
		r0 = rf(ctx, channelID, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, channelID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_LeaveVoiceChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LeaveVoiceChannel'
type MockStore_LeaveVoiceChannel_Call struct {
	*mock.Call
}

// LeaveVoiceChannel is a helper method to define mock.On call
//   - ctx context.Context
//   - channelID uuid.UUID
//   - userID uuid.UUID
func (_e *MockStore_Expecter) LeaveVoiceChannel(ctx interface{}, channelID interface{}, userID interface{}) *MockStore_LeaveVoiceChannel_Call {
	return &MockStore_LeaveVoiceChannel_Call{Call: _e.mock.On("LeaveVoiceChannel", ctx, channelID, userID)}
}

func (_c *MockStore_LeaveVoiceChannel_Call) Run(run func(ctx context.Context, channelID uuid.UUID, userID uuid.UUID)) *MockStore_LeaveVoiceChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockStore_LeaveVoiceChannel_Call) Return(_a0 bool, _a1 error) *MockStore_LeaveVoiceChannel_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_LeaveVoiceChannel_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (bool, error)) *MockStore_LeaveVoiceChannel_Call {
	_c.Call.Return(run)
	return _c
}

// ListVoiceParticipants provides a mock function with given fields: ctx, channelID
func (_m *MockStore) ListVoiceParticipants(ctx context.Context, channelID uuid.UUID) ([]uuid.UUID, error) {
	ret := _m.Called(ctx, channelID)

	if len(ret) == 0 {
		panic("no return value specified for ListVoiceParticipants")
	}

	var r0 []uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]uuid.UUID, error)); ok {
		return rf(ctx, channelID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []uuid.UUID); ok {
		r0 = rf(ctx, channelID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, channelID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockStore_ListVoiceParticipants_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListVoiceParticipants'
type MockStore_ListVoiceParticipants_Call struct {
	*mock.Call
}

// ListVoiceParticipants is a helper method to define mock.On call
//   - ctx context.Context
//   - channelID uuid.UUID
func (_e *MockStore_Expecter) ListVoiceParticipants(ctx interface{}, channelID interface{}) *MockStore_ListVoiceParticipants_Call {
	return &MockStore_ListVoiceParticipants_Call{Call: _e.mock.On("ListVoiceParticipants", ctx, channelID)}
}

func (_c *MockStore_ListVoiceParticipants_Call) Run(run func(ctx context.Context, channelID uuid.UUID)) *MockStore_ListVoiceParticipants_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockStore_ListVoiceParticipants_Call) Return(_a0 []uuid.UUID, _a1 error) *MockStore_ListVoiceParticipants_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockStore_ListVoiceParticipants_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]uuid.UUID, error)) *MockStore_ListVoiceParticipants_Call {
	_c.Call.Return(run)
	return _c
}

// Publish provides a mock function with given fields: ctx, topic, payload
func (_m *MockStore) Publish(ctx context.Context, topic string, payload []byte) error {
	ret := _m.Called(ctx, topic, payload)

	if len(ret) == 0 {
		panic("no return value specified for Publish")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte) error); ok {
		r0 = rf(ctx, topic, payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockStore_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - topic string
//   - payload []byte
func (_e *MockStore_Expecter) Publish(ctx interface{}, topic interface{}, payload interface{}) *MockStore_Publish_Call {
	return &MockStore_Publish_Call{Call: _e.mock.On("Publish", ctx, topic, payload)}
}

func (_c *MockStore_Publish_Call) Run(run func(ctx context.Context, topic string, payload []byte)) *MockStore_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]byte))
	})
	return _c
}

func (_c *MockStore_Publish_Call) Return(_a0 error) *MockStore_Publish_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_Publish_Call) RunAndReturn(run func(context.Context, string, []byte) error) *MockStore_Publish_Call {
	_c.Call.Return(run)
	return _c
}

// SetUserOffline provides a mock function with given fields: ctx, userID
func (_m *MockStore) SetUserOffline(ctx context.Context, userID uuid.UUID) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for SetUserOffline")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_SetUserOffline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetUserOffline'
type MockStore_SetUserOffline_Call struct {
	*mock.Call
}

// SetUserOffline is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockStore_Expecter) SetUserOffline(ctx interface{}, userID interface{}) *MockStore_SetUserOffline_Call {
	return &MockStore_SetUserOffline_Call{Call: _e.mock.On("SetUserOffline", ctx, userID)}
}

func (_c *MockStore_SetUserOffline_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockStore_SetUserOffline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockStore_SetUserOffline_Call) Return(_a0 error) *MockStore_SetUserOffline_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_SetUserOffline_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockStore_SetUserOffline_Call {
	_c.Call.Return(run)
	return _c
}

// SetUserOnline provides a mock function with given fields: ctx, userID, ttl
func (_m *MockStore) SetUserOnline(ctx context.Context, userID uuid.UUID, ttl time.Duration) error {
	ret := _m.Called(ctx, userID, ttl)

	if len(ret) == 0 {
		panic("no return value specified for SetUserOnline")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, time.Duration) error); ok {
		r0 = rf(ctx, userID, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_SetUserOnline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetUserOnline'
type MockStore_SetUserOnline_Call struct {
	*mock.Call
}

// SetUserOnline is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - ttl time.Duration
func (_e *MockStore_Expecter) SetUserOnline(ctx interface{}, userID interface{}, ttl interface{}) *MockStore_SetUserOnline_Call {
	return &MockStore_SetUserOnline_Call{Call: _e.mock.On("SetUserOnline", ctx, userID, ttl)}
}

func (_c *MockStore_SetUserOnline_Call) Run(run func(ctx context.Context, userID uuid.UUID, ttl time.Duration)) *MockStore_SetUserOnline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(time.Duration))
	})
	return _c
}

func (_c *MockStore_SetUserOnline_Call) Return(_a0 error) *MockStore_SetUserOnline_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_SetUserOnline_Call) RunAndReturn(run func(context.Context, uuid.UUID, time.Duration) error) *MockStore_SetUserOnline_Call {
	_c.Call.Return(run)
	return _c
}

// SetVoiceParticipantState provides a mock function with given fields: ctx, channelID, userID, state
func (_m *MockStore) SetVoiceParticipantState(ctx context.Context, channelID uuid.UUID, userID uuid.UUID, state realtime.VoiceParticipantState) error {
	ret := _m.Called(ctx, channelID, userID, state)

	if len(ret) == 0 {
		panic("no return value specified for SetVoiceParticipantState")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, realtime.VoiceParticipantState) error); ok {
		r0 = rf(ctx, channelID, userID, state)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockStore_SetVoiceParticipantState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetVoiceParticipantState'
type MockStore_SetVoiceParticipantState_Call struct {
	*mock.Call
}

// SetVoiceParticipantState is a helper method to define mock.On call
//   - ctx context.Context
//   - channelID uuid.UUID
//   - userID uuid.UUID
//   - state realtime.VoiceParticipantState
func (_e *MockStore_Expecter) SetVoiceParticipantState(ctx interface{}, channelID interface{}, userID interface{}, state interface{}) *MockStore_SetVoiceParticipantState_Call {
	return &MockStore_SetVoiceParticipantState_Call{Call: _e.mock.On("SetVoiceParticipantState", ctx, channelID, userID, state)}
}

func (_c *MockStore_SetVoiceParticipantState_Call) Run(run func(ctx context.Context, channelID uuid.UUID, userID uuid.UUID, state realtime.VoiceParticipantState)) *MockStore_SetVoiceParticipantState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(realtime.VoiceParticipantState))
	})
	return _c
}

func (_c *MockStore_SetVoiceParticipantState_Call) Return(_a0 error) *MockStore_SetVoiceParticipantState_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockStore_SetVoiceParticipantState_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, realtime.VoiceParticipantState) error) *MockStore_SetVoiceParticipantState_Call {
	_c.Call.Return(run)
	return _c
}

// Subscribe provides a mock function with given fields: ctx, topics
func (_m *MockStore) Subscribe(ctx context.Context, topics []string) (<-chan realtime.Envelope, func(), error) {
	ret := _m.Called(ctx, topics)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 <-chan realtime.Envelope
	var r1 func()
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) (<-chan realtime.Envelope, func(), error)); ok {
		return rf(ctx, topics)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) <-chan realtime.Envelope); ok {
		r0 = rf(ctx, topics)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan realtime.Envelope)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) func()); ok {
		r1 = rf(ctx, topics)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(func())
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, []string) error); ok {
		r2 = rf(ctx, topics)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockStore_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockStore_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - ctx context.Context
//   - topics []string
func (_e *MockStore_Expecter) Subscribe(ctx interface{}, topics interface{}) *MockStore_Subscribe_Call {
	return &MockStore_Subscribe_Call{Call: _e.mock.On("Subscribe", ctx, topics)}
}

func (_c *MockStore_Subscribe_Call) Run(run func(ctx context.Context, topics []string)) *MockStore_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockStore_Subscribe_Call) Return(_a0 <-chan realtime.Envelope, _a1 func(), _a2 error) *MockStore_Subscribe_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockStore_Subscribe_Call) RunAndReturn(run func(context.Context, []string) (<-chan realtime.Envelope, func(), error)) *MockStore_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockStore creates a new instance of MockStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockStore {
	mock := &MockStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
