// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockPublisher is an autogenerated mock type for the Publisher type
type MockPublisher struct {
	mock.Mock
}

type MockPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPublisher) EXPECT() *MockPublisher_Expecter {
	return &MockPublisher_Expecter{mock: &_m.Mock}
}

// PublishMessageCreated provides a mock function with given fields: ctx, topic, message
func (_m *MockPublisher) PublishMessageCreated(ctx context.Context, topic string, message any) error {
	ret := _m.Called(ctx, topic, message)

	if len(ret) == 0 {
		panic("no return value specified for PublishMessageCreated")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, any) error); ok {
		r0 = rf(ctx, topic, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPublisher_PublishMessageCreated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishMessageCreated'
type MockPublisher_PublishMessageCreated_Call struct {
	*mock.Call
}

// PublishMessageCreated is a helper method to define mock.On call
//   - ctx context.Context
//   - topic string
//   - message any
func (_e *MockPublisher_Expecter) PublishMessageCreated(ctx interface{}, topic interface{}, message interface{}) *MockPublisher_PublishMessageCreated_Call {
	return &MockPublisher_PublishMessageCreated_Call{Call: _e.mock.On("PublishMessageCreated", ctx, topic, message)}
}

func (_c *MockPublisher_PublishMessageCreated_Call) Run(run func(ctx context.Context, topic string, message any)) *MockPublisher_PublishMessageCreated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(any))
	})
	return _c
}

func (_c *MockPublisher_PublishMessageCreated_Call) Return(_a0 error) *MockPublisher_PublishMessageCreated_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPublisher_PublishMessageCreated_Call) RunAndReturn(run func(context.Context, string, any) error) *MockPublisher_PublishMessageCreated_Call {
	_c.Call.Return(run)
	return _c
}

// PublishMessageRead provides a mock function with given fields: ctx, topic, receipt
func (_m *MockPublisher) PublishMessageRead(ctx context.Context, topic string, receipt any) error {
	ret := _m.Called(ctx, topic, receipt)

	if len(ret) == 0 {
		panic("no return value specified for PublishMessageRead")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, any) error); ok {
		r0 = rf(ctx, topic, receipt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockPublisher_PublishMessageRead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishMessageRead'
type MockPublisher_PublishMessageRead_Call struct {
	*mock.Call
}

// PublishMessageRead is a helper method to define mock.On call
//   - ctx context.Context
//   - topic string
//   - receipt any
func (_e *MockPublisher_Expecter) PublishMessageRead(ctx interface{}, topic interface{}, receipt interface{}) *MockPublisher_PublishMessageRead_Call {
	return &MockPublisher_PublishMessageRead_Call{Call: _e.mock.On("PublishMessageRead", ctx, topic, receipt)}
}

func (_c *MockPublisher_PublishMessageRead_Call) Run(run func(ctx context.Context, topic string, receipt any)) *MockPublisher_PublishMessageRead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(any))
	})
	return _c
}

func (_c *MockPublisher_PublishMessageRead_Call) Return(_a0 error) *MockPublisher_PublishMessageRead_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockPublisher_PublishMessageRead_Call) RunAndReturn(run func(context.Context, string, any) error) *MockPublisher_PublishMessageRead_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockPublisher creates a new instance of MockPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPublisher {
	mock := &MockPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
