// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	chat "zchat/internal/chat"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// CreateChannelMessage provides a mock function with given fields: ctx, message
func (_m *MockRepository) CreateChannelMessage(ctx context.Context, message *chat.Message) error {
	ret := _m.Called(ctx, message)

	if len(ret) == 0 {
		panic("no return value specified for CreateChannelMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *chat.Message) error); ok {
		r0 = rf(ctx, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_CreateChannelMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateChannelMessage'
type MockRepository_CreateChannelMessage_Call struct {
	*mock.Call
}

// CreateChannelMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - message *chat.Message
func (_e *MockRepository_Expecter) CreateChannelMessage(ctx interface{}, message interface{}) *MockRepository_CreateChannelMessage_Call {
	return &MockRepository_CreateChannelMessage_Call{Call: _e.mock.On("CreateChannelMessage", ctx, message)}
}

func (_c *MockRepository_CreateChannelMessage_Call) Run(run func(ctx context.Context, message *chat.Message)) *MockRepository_CreateChannelMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*chat.Message))
	})
	return _c
}

func (_c *MockRepository_CreateChannelMessage_Call) Return(_a0 error) *MockRepository_CreateChannelMessage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_CreateChannelMessage_Call) RunAndReturn(run func(context.Context, *chat.Message) error) *MockRepository_CreateChannelMessage_Call {
	_c.Call.Return(run)
	return _c
}

// CreateDirectMessage provides a mock function with given fields: ctx, message
func (_m *MockRepository) CreateDirectMessage(ctx context.Context, message *chat.Message) error {
	ret := _m.Called(ctx, message)

	if len(ret) == 0 {
		panic("no return value specified for CreateDirectMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *chat.Message) error); ok {
		r0 = rf(ctx, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_CreateDirectMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateDirectMessage'
type MockRepository_CreateDirectMessage_Call struct {
	*mock.Call
}

// CreateDirectMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - message *chat.Message
func (_e *MockRepository_Expecter) CreateDirectMessage(ctx interface{}, message interface{}) *MockRepository_CreateDirectMessage_Call {
	return &MockRepository_CreateDirectMessage_Call{Call: _e.mock.On("CreateDirectMessage", ctx, message)}
}

func (_c *MockRepository_CreateDirectMessage_Call) Run(run func(ctx context.Context, message *chat.Message)) *MockRepository_CreateDirectMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*chat.Message))
	})
	return _c
}

func (_c *MockRepository_CreateDirectMessage_Call) Return(_a0 error) *MockRepository_CreateDirectMessage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_CreateDirectMessage_Call) RunAndReturn(run func(context.Context, *chat.Message) error) *MockRepository_CreateDirectMessage_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOrGetDirectChat provides a mock function with given fields: ctx, user1, user2
func (_m *MockRepository) CreateOrGetDirectChat(ctx context.Context, user1 uuid.UUID, user2 uuid.UUID) (*chat.DirectChat, error) {
	ret := _m.Called(ctx, user1, user2)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrGetDirectChat")
	}

	var r0 *chat.DirectChat
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*chat.DirectChat, error)); ok {
		return rf(ctx, user1, user2)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *chat.DirectChat); ok {
		r0 = rf(ctx, user1, user2)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*chat.DirectChat)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, user1, user2)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_CreateOrGetDirectChat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrGetDirectChat'
type MockRepository_CreateOrGetDirectChat_Call struct {
	*mock.Call
}

// CreateOrGetDirectChat is a helper method to define mock.On call
//   - ctx context.Context
//   - user1 uuid.UUID
//   - user2 uuid.UUID
func (_e *MockRepository_Expecter) CreateOrGetDirectChat(ctx interface{}, user1 interface{}, user2 interface{}) *MockRepository_CreateOrGetDirectChat_Call {
	return &MockRepository_CreateOrGetDirectChat_Call{Call: _e.mock.On("CreateOrGetDirectChat", ctx, user1, user2)}
}

func (_c *MockRepository_CreateOrGetDirectChat_Call) Run(run func(ctx context.Context, user1 uuid.UUID, user2 uuid.UUID)) *MockRepository_CreateOrGetDirectChat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_CreateOrGetDirectChat_Call) Return(_a0 *chat.DirectChat, _a1 error) *MockRepository_CreateOrGetDirectChat_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_CreateOrGetDirectChat_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (*chat.DirectChat, error)) *MockRepository_CreateOrGetDirectChat_Call {
	_c.Call.Return(run)
	return _c
}

// GetMessageByID provides a mock function with given fields: ctx, messageID
func (_m *MockRepository) GetMessageByID(ctx context.Context, messageID uuid.UUID) (*chat.Message, error) {
	ret := _m.Called(ctx, messageID)

	if len(ret) == 0 {
		panic("no return value specified for GetMessageByID")
	}

	var r0 *chat.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) (*chat.Message, error)); ok {
		return rf(ctx, messageID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) *chat.Message); ok {
		r0 = rf(ctx, messageID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*chat.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, messageID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_GetMessageByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetMessageByID'
type MockRepository_GetMessageByID_Call struct {
	*mock.Call
}

// GetMessageByID is a helper method to define mock.On call
//   - ctx context.Context
//   - messageID uuid.UUID
func (_e *MockRepository_Expecter) GetMessageByID(ctx interface{}, messageID interface{}) *MockRepository_GetMessageByID_Call {
	return &MockRepository_GetMessageByID_Call{Call: _e.mock.On("GetMessageByID", ctx, messageID)}
}

func (_c *MockRepository_GetMessageByID_Call) Run(run func(ctx context.Context, messageID uuid.UUID)) *MockRepository_GetMessageByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_GetMessageByID_Call) Return(_a0 *chat.Message, _a1 error) *MockRepository_GetMessageByID_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_GetMessageByID_Call) RunAndReturn(run func(context.Context, uuid.UUID) (*chat.Message, error)) *MockRepository_GetMessageByID_Call {
	_c.Call.Return(run)
	return _c
}

// IsDirectChatMember provides a mock function with given fields: ctx, directChatID, userID
func (_m *MockRepository) IsDirectChatMember(ctx context.Context, directChatID uuid.UUID, userID uuid.UUID) (bool, error) {
	ret := _m.Called(ctx, directChatID, userID)

	if len(ret) == 0 {
		panic("no return value specified for IsDirectChatMember")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (bool, error)); ok {
		return rf(ctx, directChatID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) bool); ok {
		r0 = rf(ctx, directChatID, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, directChatID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_IsDirectChatMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsDirectChatMember'
type MockRepository_IsDirectChatMember_Call struct {
	*mock.Call
}

// IsDirectChatMember is a helper method to define mock.On call
//   - ctx context.Context
//   - directChatID uuid.UUID
//   - userID uuid.UUID
func (_e *MockRepository_Expecter) IsDirectChatMember(ctx interface{}, directChatID interface{}, userID interface{}) *MockRepository_IsDirectChatMember_Call {
	return &MockRepository_IsDirectChatMember_Call{Call: _e.mock.On("IsDirectChatMember", ctx, directChatID, userID)}
}

func (_c *MockRepository_IsDirectChatMember_Call) Run(run func(ctx context.Context, directChatID uuid.UUID, userID uuid.UUID)) *MockRepository_IsDirectChatMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_IsDirectChatMember_Call) Return(_a0 bool, _a1 error) *MockRepository_IsDirectChatMember_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_IsDirectChatMember_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (bool, error)) *MockRepository_IsDirectChatMember_Call {
	_c.Call.Return(run)
	return _c
}

// ListChannelMessages provides a mock function with given fields: ctx, channelID, limit, offset
func (_m *MockRepository) ListChannelMessages(ctx context.Context, channelID uuid.UUID, limit int, offset int) ([]chat.Message, error) {
	ret := _m.Called(ctx, channelID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListChannelMessages")
	}

	var r0 []chat.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]chat.Message, error)); ok {
		return rf(ctx, channelID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []chat.Message); ok {
		r0 = rf(ctx, channelID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]chat.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) error); ok {
		r1 = rf(ctx, channelID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListChannelMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListChannelMessages'
type MockRepository_ListChannelMessages_Call struct {
	*mock.Call
}

// ListChannelMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - channelID uuid.UUID
//   - limit int
//   - offset int
func (_e *MockRepository_Expecter) ListChannelMessages(ctx interface{}, channelID interface{}, limit interface{}, offset interface{}) *MockRepository_ListChannelMessages_Call {
	return &MockRepository_ListChannelMessages_Call{Call: _e.mock.On("ListChannelMessages", ctx, channelID, limit, offset)}
}

func (_c *MockRepository_ListChannelMessages_Call) Run(run func(ctx context.Context, channelID uuid.UUID, limit int, offset int)) *MockRepository_ListChannelMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockRepository_ListChannelMessages_Call) Return(_a0 []chat.Message, _a1 error) *MockRepository_ListChannelMessages_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListChannelMessages_Call) RunAndReturn(run func(context.Context, uuid.UUID, int, int) ([]chat.Message, error)) *MockRepository_ListChannelMessages_Call {
	_c.Call.Return(run)
	return _c
}

// ListDirectMessages provides a mock function with given fields: ctx, directChatID, limit, offset
func (_m *MockRepository) ListDirectMessages(ctx context.Context, directChatID uuid.UUID, limit int, offset int) ([]chat.Message, error) {
	ret := _m.Called(ctx, directChatID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListDirectMessages")
	}

	var r0 []chat.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) ([]chat.Message, error)); ok {
		return rf(ctx, directChatID, limit, offset)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, int) []chat.Message); ok {
		r0 = rf(ctx, directChatID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]chat.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, int) error); ok {
		r1 = rf(ctx, directChatID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRepository_ListDirectMessages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDirectMessages'
type MockRepository_ListDirectMessages_Call struct {
	*mock.Call
}

// ListDirectMessages is a helper method to define mock.On call
//   - ctx context.Context
//   - directChatID uuid.UUID
//   - limit int
//   - offset int
func (_e *MockRepository_Expecter) ListDirectMessages(ctx interface{}, directChatID interface{}, limit interface{}, offset interface{}) *MockRepository_ListDirectMessages_Call {
	return &MockRepository_ListDirectMessages_Call{Call: _e.mock.On("ListDirectMessages", ctx, directChatID, limit, offset)}
}

func (_c *MockRepository_ListDirectMessages_Call) Run(run func(ctx context.Context, directChatID uuid.UUID, limit int, offset int)) *MockRepository_ListDirectMessages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(int), args[3].(int))
	})
	return _c
}

func (_c *MockRepository_ListDirectMessages_Call) Return(_a0 []chat.Message, _a1 error) *MockRepository_ListDirectMessages_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRepository_ListDirectMessages_Call) RunAndReturn(run func(context.Context, uuid.UUID, int, int) ([]chat.Message, error)) *MockRepository_ListDirectMessages_Call {
	_c.Call.Return(run)
	return _c
}

// MarkMessagesDelivered provides a mock function with given fields: ctx, userID, messageIDs
func (_m *MockRepository) MarkMessagesDelivered(ctx context.Context, userID uuid.UUID, messageIDs []uuid.UUID) error {
	ret := _m.Called(ctx, userID, messageIDs)

	if len(ret) == 0 {
		panic("no return value specified for MarkMessagesDelivered")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, []uuid.UUID) error); ok {
		r0 = rf(ctx, userID, messageIDs)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_MarkMessagesDelivered_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkMessagesDelivered'
type MockRepository_MarkMessagesDelivered_Call struct {
	*mock.Call
}

// MarkMessagesDelivered is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - messageIDs []uuid.UUID
func (_e *MockRepository_Expecter) MarkMessagesDelivered(ctx interface{}, userID interface{}, messageIDs interface{}) *MockRepository_MarkMessagesDelivered_Call {
	return &MockRepository_MarkMessagesDelivered_Call{Call: _e.mock.On("MarkMessagesDelivered", ctx, userID, messageIDs)}
}

func (_c *MockRepository_MarkMessagesDelivered_Call) Run(run func(ctx context.Context, userID uuid.UUID, messageIDs []uuid.UUID)) *MockRepository_MarkMessagesDelivered_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].([]uuid.UUID))
	})
	return _c
}

func (_c *MockRepository_MarkMessagesDelivered_Call) Return(_a0 error) *MockRepository_MarkMessagesDelivered_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_MarkMessagesDelivered_Call) RunAndReturn(run func(context.Context, uuid.UUID, []uuid.UUID) error) *MockRepository_MarkMessagesDelivered_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertReceipt provides a mock function with given fields: ctx, receipt
func (_m *MockRepository) UpsertReceipt(ctx context.Context, receipt *chat.Receipt) error {
	ret := _m.Called(ctx, receipt)

	if len(ret) == 0 {
		panic("no return value specified for UpsertReceipt")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *chat.Receipt) error); ok {
		r0 = rf(ctx, receipt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRepository_UpsertReceipt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertReceipt'
type MockRepository_UpsertReceipt_Call struct {
	*mock.Call
}

// UpsertReceipt is a helper method to define mock.On call
//   - ctx context.Context
//   - receipt *chat.Receipt
func (_e *MockRepository_Expecter) UpsertReceipt(ctx interface{}, receipt interface{}) *MockRepository_UpsertReceipt_Call {
	return &MockRepository_UpsertReceipt_Call{Call: _e.mock.On("UpsertReceipt", ctx, receipt)}
}

func (_c *MockRepository_UpsertReceipt_Call) Run(run func(ctx context.Context, receipt *chat.Receipt)) *MockRepository_UpsertReceipt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*chat.Receipt))
	})
	return _c
}

func (_c *MockRepository_UpsertReceipt_Call) Return(_a0 error) *MockRepository_UpsertReceipt_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRepository_UpsertReceipt_Call) RunAndReturn(run func(context.Context, *chat.Receipt) error) *MockRepository_UpsertReceipt_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
