// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	uuid "github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// MockChannelAccess is an autogenerated mock type for the ChannelAccess type
type MockChannelAccess struct {
	mock.Mock
}

type MockChannelAccess_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChannelAccess) EXPECT() *MockChannelAccess_Expecter {
	return &MockChannelAccess_Expecter{mock: &_m.Mock}
}

// AssertChannelMember provides a mock function with given fields: ctx, channelID, userID
func (_m *MockChannelAccess) AssertChannelMember(ctx context.Context, channelID uuid.UUID, userID uuid.UUID) error {
	ret := _m.Called(ctx, channelID, userID)

	if len(ret) == 0 {
		panic("no return value specified for AssertChannelMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, channelID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockChannelAccess_AssertChannelMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssertChannelMember'
type MockChannelAccess_AssertChannelMember_Call struct {
	*mock.Call
}

// AssertChannelMember is a helper method to define mock.On call
//   - ctx context.Context
//   - channelID uuid.UUID
//   - userID uuid.UUID
func (_e *MockChannelAccess_Expecter) AssertChannelMember(ctx interface{}, channelID interface{}, userID interface{}) *MockChannelAccess_AssertChannelMember_Call {
	return &MockChannelAccess_AssertChannelMember_Call{Call: _e.mock.On("AssertChannelMember", ctx, channelID, userID)}
}

func (_c *MockChannelAccess_AssertChannelMember_Call) Run(run func(ctx context.Context, channelID uuid.UUID, userID uuid.UUID)) *MockChannelAccess_AssertChannelMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockChannelAccess_AssertChannelMember_Call) Return(_a0 error) *MockChannelAccess_AssertChannelMember_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChannelAccess_AssertChannelMember_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockChannelAccess_AssertChannelMember_Call {
	_c.Call.Return(run)
	return _c
}

// AssertTextChannelWriter provides a mock function with given fields: ctx, channelID, userID
func (_m *MockChannelAccess) AssertTextChannelWriter(ctx context.Context, channelID uuid.UUID, userID uuid.UUID) error {
	ret := _m.Called(ctx, channelID, userID)

	if len(ret) == 0 {
		panic("no return value specified for AssertTextChannelWriter")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, channelID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockChannelAccess_AssertTextChannelWriter_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssertTextChannelWriter'
type MockChannelAccess_AssertTextChannelWriter_Call struct {
	*mock.Call
}

// AssertTextChannelWriter is a helper method to define mock.On call
//   - ctx context.Context
//   - channelID uuid.UUID
//   - userID uuid.UUID
func (_e *MockChannelAccess_Expecter) AssertTextChannelWriter(ctx interface{}, channelID interface{}, userID interface{}) *MockChannelAccess_AssertTextChannelWriter_Call {
	return &MockChannelAccess_AssertTextChannelWriter_Call{Call: _e.mock.On("AssertTextChannelWriter", ctx, channelID, userID)}
}

func (_c *MockChannelAccess_AssertTextChannelWriter_Call) Run(run func(ctx context.Context, channelID uuid.UUID, userID uuid.UUID)) *MockChannelAccess_AssertTextChannelWriter_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockChannelAccess_AssertTextChannelWriter_Call) Return(_a0 error) *MockChannelAccess_AssertTextChannelWriter_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChannelAccess_AssertTextChannelWriter_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockChannelAccess_AssertTextChannelWriter_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockChannelAccess creates a new instance of MockChannelAccess. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChannelAccess(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChannelAccess {
	mock := &MockChannelAccess{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
