// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	chat "zchat/internal/chat"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockChatService is an autogenerated mock type for the ChatService type
type MockChatService struct {
	mock.Mock
}

type MockChatService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChatService) EXPECT() *MockChatService_Expecter {
	return &MockChatService_Expecter{mock: &_m.Mock}
}

// AssertDirectChatMember provides a mock function with given fields: ctx, directChatID, userID
func (_m *MockChatService) AssertDirectChatMember(ctx context.Context, directChatID uuid.UUID, userID uuid.UUID) error {
	ret := _m.Called(ctx, directChatID, userID)

	if len(ret) == 0 {
		panic("no return value specified for AssertDirectChatMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, directChatID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockChatService_AssertDirectChatMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssertDirectChatMember'
type MockChatService_AssertDirectChatMember_Call struct {
	*mock.Call
}

// AssertDirectChatMember is a helper method to define mock.On call
//   - ctx context.Context
//   - directChatID uuid.UUID
//   - userID uuid.UUID
func (_e *MockChatService_Expecter) AssertDirectChatMember(ctx interface{}, directChatID interface{}, userID interface{}) *MockChatService_AssertDirectChatMember_Call {
	return &MockChatService_AssertDirectChatMember_Call{Call: _e.mock.On("AssertDirectChatMember", ctx, directChatID, userID)}
}

func (_c *MockChatService_AssertDirectChatMember_Call) Run(run func(ctx context.Context, directChatID uuid.UUID, userID uuid.UUID)) *MockChatService_AssertDirectChatMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockChatService_AssertDirectChatMember_Call) Return(_a0 error) *MockChatService_AssertDirectChatMember_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockChatService_AssertDirectChatMember_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockChatService_AssertDirectChatMember_Call {
	_c.Call.Return(run)
	return _c
}

// MarkChannelMessageRead provides a mock function with given fields: ctx, input
func (_m *MockChatService) MarkChannelMessageRead(ctx context.Context, input chat.MarkChannelReadInput) (*chat.Receipt, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for MarkChannelMessageRead")
	}

	var r0 *chat.Receipt
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, chat.MarkChannelReadInput) (*chat.Receipt, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, chat.MarkChannelReadInput) *chat.Receipt); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*chat.Receipt)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, chat.MarkChannelReadInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChatService_MarkChannelMessageRead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkChannelMessageRead'
type MockChatService_MarkChannelMessageRead_Call struct {
	*mock.Call
}

// MarkChannelMessageRead is a helper method to define mock.On call
//   - ctx context.Context
//   - input chat.MarkChannelReadInput
func (_e *MockChatService_Expecter) MarkChannelMessageRead(ctx interface{}, input interface{}) *MockChatService_MarkChannelMessageRead_Call {
	return &MockChatService_MarkChannelMessageRead_Call{Call: _e.mock.On("MarkChannelMessageRead", ctx, input)}
}

func (_c *MockChatService_MarkChannelMessageRead_Call) Run(run func(ctx context.Context, input chat.MarkChannelReadInput)) *MockChatService_MarkChannelMessageRead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(chat.MarkChannelReadInput))
	})
	return _c
}

func (_c *MockChatService_MarkChannelMessageRead_Call) Return(_a0 *chat.Receipt, _a1 error) *MockChatService_MarkChannelMessageRead_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChatService_MarkChannelMessageRead_Call) RunAndReturn(run func(context.Context, chat.MarkChannelReadInput) (*chat.Receipt, error)) *MockChatService_MarkChannelMessageRead_Call {
	_c.Call.Return(run)
	return _c
}

// MarkDirectMessageRead provides a mock function with given fields: ctx, input
func (_m *MockChatService) MarkDirectMessageRead(ctx context.Context, input chat.MarkDirectReadInput) (*chat.Receipt, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for MarkDirectMessageRead")
	}

	var r0 *chat.Receipt
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, chat.MarkDirectReadInput) (*chat.Receipt, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, chat.MarkDirectReadInput) *chat.Receipt); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*chat.Receipt)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, chat.MarkDirectReadInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChatService_MarkDirectMessageRead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkDirectMessageRead'
type MockChatService_MarkDirectMessageRead_Call struct {
	*mock.Call
}

// MarkDirectMessageRead is a helper method to define mock.On call
//   - ctx context.Context
//   - input chat.MarkDirectReadInput
func (_e *MockChatService_Expecter) MarkDirectMessageRead(ctx interface{}, input interface{}) *MockChatService_MarkDirectMessageRead_Call {
	return &MockChatService_MarkDirectMessageRead_Call{Call: _e.mock.On("MarkDirectMessageRead", ctx, input)}
}

func (_c *MockChatService_MarkDirectMessageRead_Call) Run(run func(ctx context.Context, input chat.MarkDirectReadInput)) *MockChatService_MarkDirectMessageRead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(chat.MarkDirectReadInput))
	})
	return _c
}

func (_c *MockChatService_MarkDirectMessageRead_Call) Return(_a0 *chat.Receipt, _a1 error) *MockChatService_MarkDirectMessageRead_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChatService_MarkDirectMessageRead_Call) RunAndReturn(run func(context.Context, chat.MarkDirectReadInput) (*chat.Receipt, error)) *MockChatService_MarkDirectMessageRead_Call {
	_c.Call.Return(run)
	return _c
}

// SendChannelMessage provides a mock function with given fields: ctx, input
func (_m *MockChatService) SendChannelMessage(ctx context.Context, input chat.SendChannelMessageInput) (*chat.Message, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for SendChannelMessage")
	}

	var r0 *chat.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, chat.SendChannelMessageInput) (*chat.Message, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, chat.SendChannelMessageInput) *chat.Message); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*chat.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, chat.SendChannelMessageInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChatService_SendChannelMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendChannelMessage'
type MockChatService_SendChannelMessage_Call struct {
	*mock.Call
}

// SendChannelMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - input chat.SendChannelMessageInput
func (_e *MockChatService_Expecter) SendChannelMessage(ctx interface{}, input interface{}) *MockChatService_SendChannelMessage_Call {
	return &MockChatService_SendChannelMessage_Call{Call: _e.mock.On("SendChannelMessage", ctx, input)}
}

func (_c *MockChatService_SendChannelMessage_Call) Run(run func(ctx context.Context, input chat.SendChannelMessageInput)) *MockChatService_SendChannelMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(chat.SendChannelMessageInput))
	})
	return _c
}

func (_c *MockChatService_SendChannelMessage_Call) Return(_a0 *chat.Message, _a1 error) *MockChatService_SendChannelMessage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChatService_SendChannelMessage_Call) RunAndReturn(run func(context.Context, chat.SendChannelMessageInput) (*chat.Message, error)) *MockChatService_SendChannelMessage_Call {
	_c.Call.Return(run)
	return _c
}

// SendDirectMessage provides a mock function with given fields: ctx, input
func (_m *MockChatService) SendDirectMessage(ctx context.Context, input chat.SendDirectMessageInput) (*chat.Message, error) {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for SendDirectMessage")
	}

	var r0 *chat.Message
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, chat.SendDirectMessageInput) (*chat.Message, error)); ok {
		return rf(ctx, input)
	}
	if rf, ok := ret.Get(0).(func(context.Context, chat.SendDirectMessageInput) *chat.Message); ok {
		r0 = rf(ctx, input)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*chat.Message)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, chat.SendDirectMessageInput) error); ok {
		r1 = rf(ctx, input)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockChatService_SendDirectMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendDirectMessage'
type MockChatService_SendDirectMessage_Call struct {
	*mock.Call
}

// SendDirectMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - input chat.SendDirectMessageInput
func (_e *MockChatService_Expecter) SendDirectMessage(ctx interface{}, input interface{}) *MockChatService_SendDirectMessage_Call {
	return &MockChatService_SendDirectMessage_Call{Call: _e.mock.On("SendDirectMessage", ctx, input)}
}

func (_c *MockChatService_SendDirectMessage_Call) Run(run func(ctx context.Context, input chat.SendDirectMessageInput)) *MockChatService_SendDirectMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(chat.SendDirectMessageInput))
	})
	return _c
}

func (_c *MockChatService_SendDirectMessage_Call) Return(_a0 *chat.Message, _a1 error) *MockChatService_SendDirectMessage_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockChatService_SendDirectMessage_Call) RunAndReturn(run func(context.Context, chat.SendDirectMessageInput) (*chat.Message, error)) *MockChatService_SendDirectMessage_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockChatService creates a new instance of MockChatService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChatService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChatService {
	mock := &MockChatService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
