// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	group "zchat/internal/group"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockGroupService is an autogenerated mock type for the GroupService type
type MockGroupService struct {
	mock.Mock
}

type MockGroupService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGroupService) EXPECT() *MockGroupService_Expecter {
	return &MockGroupService_Expecter{mock: &_m.Mock}
}

// AssertChannelMember provides a mock function with given fields: ctx, channelID, userID
func (_m *MockGroupService) AssertChannelMember(ctx context.Context, channelID uuid.UUID, userID uuid.UUID) error {
	ret := _m.Called(ctx, channelID, userID)

	if len(ret) == 0 {
		panic("no return value specified for AssertChannelMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, channelID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGroupService_AssertChannelMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssertChannelMember'
type MockGroupService_AssertChannelMember_Call struct {
	*mock.Call
}

// AssertChannelMember is a helper method to define mock.On call
//   - ctx context.Context
//   - channelID uuid.UUID
//   - userID uuid.UUID
func (_e *MockGroupService_Expecter) AssertChannelMember(ctx interface{}, channelID interface{}, userID interface{}) *MockGroupService_AssertChannelMember_Call {
	return &MockGroupService_AssertChannelMember_Call{Call: _e.mock.On("AssertChannelMember", ctx, channelID, userID)}
}

func (_c *MockGroupService_AssertChannelMember_Call) Run(run func(ctx context.Context, channelID uuid.UUID, userID uuid.UUID)) *MockGroupService_AssertChannelMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockGroupService_AssertChannelMember_Call) Return(_a0 error) *MockGroupService_AssertChannelMember_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGroupService_AssertChannelMember_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockGroupService_AssertChannelMember_Call {
	_c.Call.Return(run)
	return _c
}

// AssertVoiceChannelMember provides a mock function with given fields: ctx, channelID, userID
func (_m *MockGroupService) AssertVoiceChannelMember(ctx context.Context, channelID uuid.UUID, userID uuid.UUID) error {
	ret := _m.Called(ctx, channelID, userID)

	if len(ret) == 0 {
		panic("no return value specified for AssertVoiceChannelMember")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, channelID, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGroupService_AssertVoiceChannelMember_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssertVoiceChannelMember'
type MockGroupService_AssertVoiceChannelMember_Call struct {
	*mock.Call
}

// AssertVoiceChannelMember is a helper method to define mock.On call
//   - ctx context.Context
//   - channelID uuid.UUID
//   - userID uuid.UUID
func (_e *MockGroupService_Expecter) AssertVoiceChannelMember(ctx interface{}, channelID interface{}, userID interface{}) *MockGroupService_AssertVoiceChannelMember_Call {
	return &MockGroupService_AssertVoiceChannelMember_Call{Call: _e.mock.On("AssertVoiceChannelMember", ctx, channelID, userID)}
}

func (_c *MockGroupService_AssertVoiceChannelMember_Call) Run(run func(ctx context.Context, channelID uuid.UUID, userID uuid.UUID)) *MockGroupService_AssertVoiceChannelMember_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockGroupService_AssertVoiceChannelMember_Call) Return(_a0 error) *MockGroupService_AssertVoiceChannelMember_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGroupService_AssertVoiceChannelMember_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) error) *MockGroupService_AssertVoiceChannelMember_Call {
	_c.Call.Return(run)
	return _c
}

// AssertVoiceModerationAllowed provides a mock function with given fields: ctx, channelID, actorUserID, targetUserID
func (_m *MockGroupService) AssertVoiceModerationAllowed(ctx context.Context, channelID uuid.UUID, actorUserID uuid.UUID, targetUserID uuid.UUID) error {
	ret := _m.Called(ctx, channelID, actorUserID, targetUserID)

	if len(ret) == 0 {
		panic("no return value specified for AssertVoiceModerationAllowed")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error); ok {
		r0 = rf(ctx, channelID, actorUserID, targetUserID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockGroupService_AssertVoiceModerationAllowed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssertVoiceModerationAllowed'
type MockGroupService_AssertVoiceModerationAllowed_Call struct {
	*mock.Call
}

// AssertVoiceModerationAllowed is a helper method to define mock.On call
//   - ctx context.Context
//   - channelID uuid.UUID
//   - actorUserID uuid.UUID
//   - targetUserID uuid.UUID
func (_e *MockGroupService_Expecter) AssertVoiceModerationAllowed(ctx interface{}, channelID interface{}, actorUserID interface{}, targetUserID interface{}) *MockGroupService_AssertVoiceModerationAllowed_Call {
	return &MockGroupService_AssertVoiceModerationAllowed_Call{Call: _e.mock.On("AssertVoiceModerationAllowed", ctx, channelID, actorUserID, targetUserID)}
}

func (_c *MockGroupService_AssertVoiceModerationAllowed_Call) Run(run func(ctx context.Context, channelID uuid.UUID, actorUserID uuid.UUID, targetUserID uuid.UUID)) *MockGroupService_AssertVoiceModerationAllowed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(uuid.UUID))
	})
	return _c
}

func (_c *MockGroupService_AssertVoiceModerationAllowed_Call) Return(_a0 error) *MockGroupService_AssertVoiceModerationAllowed_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockGroupService_AssertVoiceModerationAllowed_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, uuid.UUID) error) *MockGroupService_AssertVoiceModerationAllowed_Call {
	_c.Call.Return(run)
	return _c
}

// ListUserGroups provides a mock function with given fields: ctx, userID
func (_m *MockGroupService) ListUserGroups(ctx context.Context, userID uuid.UUID) ([]group.Group, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ListUserGroups")
	}

	var r0 []group.Group
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]group.Group, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []group.Group); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]group.Group)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockGroupService_ListUserGroups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUserGroups'
type MockGroupService_ListUserGroups_Call struct {
	*mock.Call
}

// ListUserGroups is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockGroupService_Expecter) ListUserGroups(ctx interface{}, userID interface{}) *MockGroupService_ListUserGroups_Call {
	return &MockGroupService_ListUserGroups_Call{Call: _e.mock.On("ListUserGroups", ctx, userID)}
}

func (_c *MockGroupService_ListUserGroups_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockGroupService_ListUserGroups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockGroupService_ListUserGroups_Call) Return(_a0 []group.Group, _a1 error) *MockGroupService_ListUserGroups_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGroupService_ListUserGroups_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]group.Group, error)) *MockGroupService_ListUserGroups_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGroupService creates a new instance of MockGroupService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGroupService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGroupService {
	mock := &MockGroupService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
