// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	realtime "zchat/internal/realtime"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/google/uuid"
)

// MockRealtimeBus is an autogenerated mock type for the RealtimeBus type
type MockRealtimeBus struct {
	mock.Mock
}

type MockRealtimeBus_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRealtimeBus) EXPECT() *MockRealtimeBus_Expecter {
	return &MockRealtimeBus_Expecter{mock: &_m.Mock}
}

// GetVoiceParticipantState provides a mock function with given fields: ctx, channelID, userID
func (_m *MockRealtimeBus) GetVoiceParticipantState(ctx context.Context, channelID uuid.UUID, userID uuid.UUID) (realtime.VoiceParticipantState, error) {
	ret := _m.Called(ctx, channelID, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetVoiceParticipantState")
	}

	var r0 realtime.VoiceParticipantState
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (realtime.VoiceParticipantState, error)); ok {
		return rf(ctx, channelID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) realtime.VoiceParticipantState); ok {
		r0 = rf(ctx, channelID, userID)
	} else {
		r0 = ret.Get(0).(realtime.VoiceParticipantState)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, channelID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRealtimeBus_GetVoiceParticipantState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetVoiceParticipantState'
type MockRealtimeBus_GetVoiceParticipantState_Call struct {
	*mock.Call
}

// GetVoiceParticipantState is a helper method to define mock.On call
//   - ctx context.Context
//   - channelID uuid.UUID
//   - userID uuid.UUID
func (_e *MockRealtimeBus_Expecter) GetVoiceParticipantState(ctx interface{}, channelID interface{}, userID interface{}) *MockRealtimeBus_GetVoiceParticipantState_Call {
	return &MockRealtimeBus_GetVoiceParticipantState_Call{Call: _e.mock.On("GetVoiceParticipantState", ctx, channelID, userID)}
}

func (_c *MockRealtimeBus_GetVoiceParticipantState_Call) Run(run func(ctx context.Context, channelID uuid.UUID, userID uuid.UUID)) *MockRealtimeBus_GetVoiceParticipantState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockRealtimeBus_GetVoiceParticipantState_Call) Return(_a0 realtime.VoiceParticipantState, _a1 error) *MockRealtimeBus_GetVoiceParticipantState_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRealtimeBus_GetVoiceParticipantState_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (realtime.VoiceParticipantState, error)) *MockRealtimeBus_GetVoiceParticipantState_Call {
	_c.Call.Return(run)
	return _c
}

// IsVoiceParticipant provides a mock function with given fields: ctx, channelID, userID
func (_m *MockRealtimeBus) IsVoiceParticipant(ctx context.Context, channelID uuid.UUID, userID uuid.UUID) (bool, error) {
	ret := _m.Called(ctx, channelID, userID)

	if len(ret) == 0 {
		panic("no return value specified for IsVoiceParticipant")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (bool, error)); ok {
		return rf(ctx, channelID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) bool); ok {
		r0 = rf(ctx, channelID, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, channelID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRealtimeBus_IsVoiceParticipant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsVoiceParticipant'
type MockRealtimeBus_IsVoiceParticipant_Call struct {
	*mock.Call
}

// IsVoiceParticipant is a helper method to define mock.On call
//   - ctx context.Context
//   - channelID uuid.UUID
//   - userID uuid.UUID
func (_e *MockRealtimeBus_Expecter) IsVoiceParticipant(ctx interface{}, channelID interface{}, userID interface{}) *MockRealtimeBus_IsVoiceParticipant_Call {
	return &MockRealtimeBus_IsVoiceParticipant_Call{Call: _e.mock.On("IsVoiceParticipant", ctx, channelID, userID)}
}

func (_c *MockRealtimeBus_IsVoiceParticipant_Call) Run(run func(ctx context.Context, channelID uuid.UUID, userID uuid.UUID)) *MockRealtimeBus_IsVoiceParticipant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockRealtimeBus_IsVoiceParticipant_Call) Return(_a0 bool, _a1 error) *MockRealtimeBus_IsVoiceParticipant_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRealtimeBus_IsVoiceParticipant_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (bool, error)) *MockRealtimeBus_IsVoiceParticipant_Call {
	_c.Call.Return(run)
	return _c
}

// JoinVoiceChannel provides a mock function with given fields: ctx, channelID, userID
func (_m *MockRealtimeBus) JoinVoiceChannel(ctx context.Context, channelID uuid.UUID, userID uuid.UUID) (bool, error) {
	ret := _m.Called(ctx, channelID, userID)

	if len(ret) == 0 {
		panic("no return value specified for JoinVoiceChannel")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (bool, error)); ok {
		return rf(ctx, channelID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) bool); ok {
		r0 = rf(ctx, channelID, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, channelID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRealtimeBus_JoinVoiceChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'JoinVoiceChannel'
type MockRealtimeBus_JoinVoiceChannel_Call struct {
	*mock.Call
}

// JoinVoiceChannel is a helper method to define mock.On call
//   - ctx context.Context
//   - channelID uuid.UUID
//   - userID uuid.UUID
func (_e *MockRealtimeBus_Expecter) JoinVoiceChannel(ctx interface{}, channelID interface{}, userID interface{}) *MockRealtimeBus_JoinVoiceChannel_Call {
	return &MockRealtimeBus_JoinVoiceChannel_Call{Call: _e.mock.On("JoinVoiceChannel", ctx, channelID, userID)}
}

func (_c *MockRealtimeBus_JoinVoiceChannel_Call) Run(run func(ctx context.Context, channelID uuid.UUID, userID uuid.UUID)) *MockRealtimeBus_JoinVoiceChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockRealtimeBus_JoinVoiceChannel_Call) Return(_a0 bool, _a1 error) *MockRealtimeBus_JoinVoiceChannel_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRealtimeBus_JoinVoiceChannel_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (bool, error)) *MockRealtimeBus_JoinVoiceChannel_Call {
	_c.Call.Return(run)
	return _c
}

// LeaveVoiceChannel provides a mock function with given fields: ctx, channelID, userID
func (_m *MockRealtimeBus) LeaveVoiceChannel(ctx context.Context, channelID uuid.UUID, userID uuid.UUID) (bool, error) {
	ret := _m.Called(ctx, channelID, userID)

	if len(ret) == 0 {
		panic("no return value specified for LeaveVoiceChannel")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (bool, error)); ok {
		return rf(ctx, channelID, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) bool); ok {
		r0 = rf(ctx, channelID, userID)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = rf(ctx, channelID, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRealtimeBus_LeaveVoiceChannel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LeaveVoiceChannel'
type MockRealtimeBus_LeaveVoiceChannel_Call struct {
	*mock.Call
}

// LeaveVoiceChannel is a helper method to define mock.On call
//   - ctx context.Context
//   - channelID uuid.UUID
//   - userID uuid.UUID
func (_e *MockRealtimeBus_Expecter) LeaveVoiceChannel(ctx interface{}, channelID interface{}, userID interface{}) *MockRealtimeBus_LeaveVoiceChannel_Call {
	return &MockRealtimeBus_LeaveVoiceChannel_Call{Call: _e.mock.On("LeaveVoiceChannel", ctx, channelID, userID)}
}

func (_c *MockRealtimeBus_LeaveVoiceChannel_Call) Run(run func(ctx context.Context, channelID uuid.UUID, userID uuid.UUID)) *MockRealtimeBus_LeaveVoiceChannel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID))
	})
	return _c
}

func (_c *MockRealtimeBus_LeaveVoiceChannel_Call) Return(_a0 bool, _a1 error) *MockRealtimeBus_LeaveVoiceChannel_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRealtimeBus_LeaveVoiceChannel_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID) (bool, error)) *MockRealtimeBus_LeaveVoiceChannel_Call {
	_c.Call.Return(run)
	return _c
}

// ListVoiceParticipants provides a mock function with given fields: ctx, channelID
func (_m *MockRealtimeBus) ListVoiceParticipants(ctx context.Context, channelID uuid.UUID) ([]uuid.UUID, error) {
	ret := _m.Called(ctx, channelID)

	if len(ret) == 0 {
		panic("no return value specified for ListVoiceParticipants")
	}

	var r0 []uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) ([]uuid.UUID, error)); ok {
		return rf(ctx, channelID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) []uuid.UUID); ok {
		r0 = rf(ctx, channelID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = rf(ctx, channelID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockRealtimeBus_ListVoiceParticipants_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListVoiceParticipants'
type MockRealtimeBus_ListVoiceParticipants_Call struct {
	*mock.Call
}

// ListVoiceParticipants is a helper method to define mock.On call
//   - ctx context.Context
//   - channelID uuid.UUID
func (_e *MockRealtimeBus_Expecter) ListVoiceParticipants(ctx interface{}, channelID interface{}) *MockRealtimeBus_ListVoiceParticipants_Call {
	return &MockRealtimeBus_ListVoiceParticipants_Call{Call: _e.mock.On("ListVoiceParticipants", ctx, channelID)}
}

func (_c *MockRealtimeBus_ListVoiceParticipants_Call) Run(run func(ctx context.Context, channelID uuid.UUID)) *MockRealtimeBus_ListVoiceParticipants_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRealtimeBus_ListVoiceParticipants_Call) Return(_a0 []uuid.UUID, _a1 error) *MockRealtimeBus_ListVoiceParticipants_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockRealtimeBus_ListVoiceParticipants_Call) RunAndReturn(run func(context.Context, uuid.UUID) ([]uuid.UUID, error)) *MockRealtimeBus_ListVoiceParticipants_Call {
	_c.Call.Return(run)
	return _c
}

// MarkOffline provides a mock function with given fields: ctx, userID
func (_m *MockRealtimeBus) MarkOffline(ctx context.Context, userID uuid.UUID) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkOffline")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRealtimeBus_MarkOffline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkOffline'
type MockRealtimeBus_MarkOffline_Call struct {
	*mock.Call
}

// MarkOffline is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockRealtimeBus_Expecter) MarkOffline(ctx interface{}, userID interface{}) *MockRealtimeBus_MarkOffline_Call {
	return &MockRealtimeBus_MarkOffline_Call{Call: _e.mock.On("MarkOffline", ctx, userID)}
}

func (_c *MockRealtimeBus_MarkOffline_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockRealtimeBus_MarkOffline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRealtimeBus_MarkOffline_Call) Return(_a0 error) *MockRealtimeBus_MarkOffline_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRealtimeBus_MarkOffline_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockRealtimeBus_MarkOffline_Call {
	_c.Call.Return(run)
	return _c
}

// MarkOnline provides a mock function with given fields: ctx, userID
func (_m *MockRealtimeBus) MarkOnline(ctx context.Context, userID uuid.UUID) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for MarkOnline")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRealtimeBus_MarkOnline_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkOnline'
type MockRealtimeBus_MarkOnline_Call struct {
	*mock.Call
}

// MarkOnline is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockRealtimeBus_Expecter) MarkOnline(ctx interface{}, userID interface{}) *MockRealtimeBus_MarkOnline_Call {
	return &MockRealtimeBus_MarkOnline_Call{Call: _e.mock.On("MarkOnline", ctx, userID)}
}

func (_c *MockRealtimeBus_MarkOnline_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockRealtimeBus_MarkOnline_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID))
	})
	return _c
}

func (_c *MockRealtimeBus_MarkOnline_Call) Return(_a0 error) *MockRealtimeBus_MarkOnline_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRealtimeBus_MarkOnline_Call) RunAndReturn(run func(context.Context, uuid.UUID) error) *MockRealtimeBus_MarkOnline_Call {
	_c.Call.Return(run)
	return _c
}

// PublishMessageCreated provides a mock function with given fields: ctx, topic, message
func (_m *MockRealtimeBus) PublishMessageCreated(ctx context.Context, topic string, message any) error {
	ret := _m.Called(ctx, topic, message)

	if len(ret) == 0 {
		panic("no return value specified for PublishMessageCreated")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, any) error); ok {
		r0 = rf(ctx, topic, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRealtimeBus_PublishMessageCreated_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishMessageCreated'
type MockRealtimeBus_PublishMessageCreated_Call struct {
	*mock.Call
}

// PublishMessageCreated is a helper method to define mock.On call
//   - ctx context.Context
//   - topic string
//   - message any
func (_e *MockRealtimeBus_Expecter) PublishMessageCreated(ctx interface{}, topic interface{}, message interface{}) *MockRealtimeBus_PublishMessageCreated_Call {
	return &MockRealtimeBus_PublishMessageCreated_Call{Call: _e.mock.On("PublishMessageCreated", ctx, topic, message)}
}

func (_c *MockRealtimeBus_PublishMessageCreated_Call) Run(run func(ctx context.Context, topic string, message any)) *MockRealtimeBus_PublishMessageCreated_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(any))
	})
	return _c
}

func (_c *MockRealtimeBus_PublishMessageCreated_Call) Return(_a0 error) *MockRealtimeBus_PublishMessageCreated_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRealtimeBus_PublishMessageCreated_Call) RunAndReturn(run func(context.Context, string, any) error) *MockRealtimeBus_PublishMessageCreated_Call {
	_c.Call.Return(run)
	return _c
}

// PublishMessageRead provides a mock function with given fields: ctx, topic, receipt
func (_m *MockRealtimeBus) PublishMessageRead(ctx context.Context, topic string, receipt any) error {
	ret := _m.Called(ctx, topic, receipt)

	if len(ret) == 0 {
		panic("no return value specified for PublishMessageRead")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, any) error); ok {
		r0 = rf(ctx, topic, receipt)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRealtimeBus_PublishMessageRead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishMessageRead'
type MockRealtimeBus_PublishMessageRead_Call struct {
	*mock.Call
}

// PublishMessageRead is a helper method to define mock.On call
//   - ctx context.Context
//   - topic string
//   - receipt any
func (_e *MockRealtimeBus_Expecter) PublishMessageRead(ctx interface{}, topic interface{}, receipt interface{}) *MockRealtimeBus_PublishMessageRead_Call {
	return &MockRealtimeBus_PublishMessageRead_Call{Call: _e.mock.On("PublishMessageRead", ctx, topic, receipt)}
}

func (_c *MockRealtimeBus_PublishMessageRead_Call) Run(run func(ctx context.Context, topic string, receipt any)) *MockRealtimeBus_PublishMessageRead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(any))
	})
	return _c
}

func (_c *MockRealtimeBus_PublishMessageRead_Call) Return(_a0 error) *MockRealtimeBus_PublishMessageRead_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRealtimeBus_PublishMessageRead_Call) RunAndReturn(run func(context.Context, string, any) error) *MockRealtimeBus_PublishMessageRead_Call {
	_c.Call.Return(run)
	return _c
}

// PublishPresenceChanged provides a mock function with given fields: ctx, topic, presence
func (_m *MockRealtimeBus) PublishPresenceChanged(ctx context.Context, topic string, presence realtime.Presence) error {
	ret := _m.Called(ctx, topic, presence)

	if len(ret) == 0 {
		panic("no return value specified for PublishPresenceChanged")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, realtime.Presence) error); ok {
		r0 = rf(ctx, topic, presence)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRealtimeBus_PublishPresenceChanged_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishPresenceChanged'
type MockRealtimeBus_PublishPresenceChanged_Call struct {
	*mock.Call
}

// PublishPresenceChanged is a helper method to define mock.On call
//   - ctx context.Context
//   - topic string
//   - presence realtime.Presence
func (_e *MockRealtimeBus_Expecter) PublishPresenceChanged(ctx interface{}, topic interface{}, presence interface{}) *MockRealtimeBus_PublishPresenceChanged_Call {
	return &MockRealtimeBus_PublishPresenceChanged_Call{Call: _e.mock.On("PublishPresenceChanged", ctx, topic, presence)}
}

func (_c *MockRealtimeBus_PublishPresenceChanged_Call) Run(run func(ctx context.Context, topic string, presence realtime.Presence)) *MockRealtimeBus_PublishPresenceChanged_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(realtime.Presence))
	})
	return _c
}

func (_c *MockRealtimeBus_PublishPresenceChanged_Call) Return(_a0 error) *MockRealtimeBus_PublishPresenceChanged_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRealtimeBus_PublishPresenceChanged_Call) RunAndReturn(run func(context.Context, string, realtime.Presence) error) *MockRealtimeBus_PublishPresenceChanged_Call {
	_c.Call.Return(run)
	return _c
}

// PublishVoiceSignaling provides a mock function with given fields: ctx, topic, eventType, payload
func (_m *MockRealtimeBus) PublishVoiceSignaling(ctx context.Context, topic string, eventType string, payload any) error {
	ret := _m.Called(ctx, topic, eventType, payload)

	if len(ret) == 0 {
		panic("no return value specified for PublishVoiceSignaling")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, any) error); ok {
		r0 = rf(ctx, topic, eventType, payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRealtimeBus_PublishVoiceSignaling_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PublishVoiceSignaling'
type MockRealtimeBus_PublishVoiceSignaling_Call struct {
	*mock.Call
}

// PublishVoiceSignaling is a helper method to define mock.On call
//   - ctx context.Context
//   - topic string
//   - eventType string
//   - payload any
func (_e *MockRealtimeBus_Expecter) PublishVoiceSignaling(ctx interface{}, topic interface{}, eventType interface{}, payload interface{}) *MockRealtimeBus_PublishVoiceSignaling_Call {
	return &MockRealtimeBus_PublishVoiceSignaling_Call{Call: _e.mock.On("PublishVoiceSignaling", ctx, topic, eventType, payload)}
}

func (_c *MockRealtimeBus_PublishVoiceSignaling_Call) Run(run func(ctx context.Context, topic string, eventType string, payload any)) *MockRealtimeBus_PublishVoiceSignaling_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(any))
	})
	return _c
}

func (_c *MockRealtimeBus_PublishVoiceSignaling_Call) Return(_a0 error) *MockRealtimeBus_PublishVoiceSignaling_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRealtimeBus_PublishVoiceSignaling_Call) RunAndReturn(run func(context.Context, string, string, any) error) *MockRealtimeBus_PublishVoiceSignaling_Call {
	_c.Call.Return(run)
	return _c
}

// SetVoiceParticipantState provides a mock function with given fields: ctx, channelID, userID, state
func (_m *MockRealtimeBus) SetVoiceParticipantState(ctx context.Context, channelID uuid.UUID, userID uuid.UUID, state realtime.VoiceParticipantState) error {
	ret := _m.Called(ctx, channelID, userID, state)

	if len(ret) == 0 {
		panic("no return value specified for SetVoiceParticipantState")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, realtime.VoiceParticipantState) error); ok {
		r0 = rf(ctx, channelID, userID, state)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockRealtimeBus_SetVoiceParticipantState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetVoiceParticipantState'
type MockRealtimeBus_SetVoiceParticipantState_Call struct {
	*mock.Call
}

// SetVoiceParticipantState is a helper method to define mock.On call
//   - ctx context.Context
//   - channelID uuid.UUID
//   - userID uuid.UUID
//   - state realtime.VoiceParticipantState
func (_e *MockRealtimeBus_Expecter) SetVoiceParticipantState(ctx interface{}, channelID interface{}, userID interface{}, state interface{}) *MockRealtimeBus_SetVoiceParticipantState_Call {
	return &MockRealtimeBus_SetVoiceParticipantState_Call{Call: _e.mock.On("SetVoiceParticipantState", ctx, channelID, userID, state)}
}

func (_c *MockRealtimeBus_SetVoiceParticipantState_Call) Run(run func(ctx context.Context, channelID uuid.UUID, userID uuid.UUID, state realtime.VoiceParticipantState)) *MockRealtimeBus_SetVoiceParticipantState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(uuid.UUID), args[2].(uuid.UUID), args[3].(realtime.VoiceParticipantState))
	})
	return _c
}

func (_c *MockRealtimeBus_SetVoiceParticipantState_Call) Return(_a0 error) *MockRealtimeBus_SetVoiceParticipantState_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockRealtimeBus_SetVoiceParticipantState_Call) RunAndReturn(run func(context.Context, uuid.UUID, uuid.UUID, realtime.VoiceParticipantState) error) *MockRealtimeBus_SetVoiceParticipantState_Call {
	_c.Call.Return(run)
	return _c
}

// Subscribe provides a mock function with given fields: ctx, topics
func (_m *MockRealtimeBus) Subscribe(ctx context.Context, topics []string) (<-chan realtime.Envelope, func(), error) {
	ret := _m.Called(ctx, topics)

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 <-chan realtime.Envelope
	var r1 func()
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) (<-chan realtime.Envelope, func(), error)); ok {
		return rf(ctx, topics)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) <-chan realtime.Envelope); ok {
		r0 = rf(ctx, topics)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan realtime.Envelope)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) func()); ok {
		r1 = rf(ctx, topics)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(func())
		}
	}

	if rf, ok := ret.Get(2).(func(context.Context, []string) error); ok {
		r2 = rf(ctx, topics)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// MockRealtimeBus_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockRealtimeBus_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
//   - ctx context.Context
//   - topics []string
func (_e *MockRealtimeBus_Expecter) Subscribe(ctx interface{}, topics interface{}) *MockRealtimeBus_Subscribe_Call {
	return &MockRealtimeBus_Subscribe_Call{Call: _e.mock.On("Subscribe", ctx, topics)}
}

func (_c *MockRealtimeBus_Subscribe_Call) Run(run func(ctx context.Context, topics []string)) *MockRealtimeBus_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].([]string))
	})
	return _c
}

func (_c *MockRealtimeBus_Subscribe_Call) Return(_a0 <-chan realtime.Envelope, _a1 func(), _a2 error) *MockRealtimeBus_Subscribe_Call {
	_c.Call.Return(_a0, _a1, _a2)
	return _c
}

func (_c *MockRealtimeBus_Subscribe_Call) RunAndReturn(run func(context.Context, []string) (<-chan realtime.Envelope, func(), error)) *MockRealtimeBus_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockRealtimeBus creates a new instance of MockRealtimeBus. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRealtimeBus(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRealtimeBus {
	mock := &MockRealtimeBus{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
