// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"
	voice "zchat/internal/voice"

	mock "github.com/stretchr/testify/mock"
)

// MockVoiceAudit is an autogenerated mock type for the VoiceAudit type
type MockVoiceAudit struct {
	mock.Mock
}

type MockVoiceAudit_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVoiceAudit) EXPECT() *MockVoiceAudit_Expecter {
	return &MockVoiceAudit_Expecter{mock: &_m.Mock}
}

// LogAction provides a mock function with given fields: ctx, input
func (_m *MockVoiceAudit) LogAction(ctx context.Context, input voice.LogActionInput) error {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for LogAction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, voice.LogActionInput) error); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockVoiceAudit_LogAction_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LogAction'
type MockVoiceAudit_LogAction_Call struct {
	*mock.Call
}

// LogAction is a helper method to define mock.On call
//   - ctx context.Context
//   - input voice.LogActionInput
func (_e *MockVoiceAudit_Expecter) LogAction(ctx interface{}, input interface{}) *MockVoiceAudit_LogAction_Call {
	return &MockVoiceAudit_LogAction_Call{Call: _e.mock.On("LogAction", ctx, input)}
}

func (_c *MockVoiceAudit_LogAction_Call) Run(run func(ctx context.Context, input voice.LogActionInput)) *MockVoiceAudit_LogAction_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(voice.LogActionInput))
	})
	return _c
}

func (_c *MockVoiceAudit_LogAction_Call) Return(_a0 error) *MockVoiceAudit_LogAction_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockVoiceAudit_LogAction_Call) RunAndReturn(run func(context.Context, voice.LogActionInput) error) *MockVoiceAudit_LogAction_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockVoiceAudit creates a new instance of MockVoiceAudit. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVoiceAudit(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVoiceAudit {
	mock := &MockVoiceAudit{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
